### ISSUE TITLE
inconvenient event handler/params:  preconfirm, onClose, and event handling with promises

### ISSUE THREAD

**Issue by kimyu92** [sweetalert2/sweetalert2#1119]
When using confirm and cancel buttons,

#### inconvenient 1: preconfirm params doesn't have current target and there is also no way to pass down data from preConfirm to onClose or to promises.
expected:
```js
let myKey = null; // current workaround
swal({
  preConfirm: (currentImplementation, currentDom/currentTarget) => {
    console.log(1);
    myKey = 1;
    return Promise.resolve({ someKey: 1 });
  }),
}).then((result) => {
  console.log(2);
  console.log(myKey); // 1
  const { someKey } = result; // eg. it will be cool to support merging/extending result or introduce one more param
});
```

#### inconvenient 2: Same as above, passing data from onClose to `.then` is not possible. Also, It will be helpful to add param to `onClose` to expose current button (target) or click event (which enable to retrieve back button)
expected: 
```js
swal({
  onClose: (currentDom, event/btn) => {
    // or
    // const btn = event.target;
  }),
});
```

**Comment by limonte** [comment]
The first part of your issue is working exactly like you're expecting it to: https://jsfiddle.net/ad3quksn/1190/

The second part will not be implemented, sorry. The popup can be closed in many ways (keyboard, mouse, timer) and passing the event or DOM node does not make much sense because they could be very different.
