### ISSUE TITLE
[Re] Proper way to override scss variables on angular

### ISSUE THREAD

**Issue by darron1217** [sweetalert2/sweetalert2#1137]
Following #1136

Here's stackblitz https://stackblitz.com/edit/angular-3c6or3?file=src%2Fstyles.scss

----------------Original Contents----------------

On angular, I use `style.scss` file to customie plugins

I thought the code below would work, but it didn't
```scss
$swal2-font-size: 1.5rem;
@import '~sweetalert2/src/sweetalert2';
```
Only with `!important` worked.
```scss
$swal2-font-size: 1.5rem !important;
@import '~sweetalert2/src/sweetalert2';
```

Is it a proper way to override scss variable?

**Comment by limonte** [comment]
Thanks for the proper issue-report @darron1217! Proper issue-report almost always leads to the proper help :)

First of all, the working stackblitz: https://stackblitz.com/edit/angular-rds9ir?file=src%2Fapp%2Fapp.component.ts

I replaced

```js
import swal from 'sweetalert2';
```

with 

```js
import swal from 'sweetalert2/src/sweetalert2.js';
```

By doing `import swal from 'sweetalert2'` you're importing **both** JS and default CSS. Since you don't want the default CSS, you need JS only which is `sweetalert2/src/sweetalert2.js`.

Documentation: https://sweetalert2.github.io/#usage

Example: https://github.com/sweetalert2/sweetalert2-parcel-demo/blob/master/app.js#L1
