### ISSUE TITLE
Unable to import from `src/sweetalert2.js`

### ISSUE THREAD

**Issue by richardhsueh** [sweetalert2/sweetalert2#1281]
I am using version 7.28.12 with react@16.6.0 
First I import it like this
```
import Swal from 'sweetalert2';
```

Next i have a function to toggle the alert
```
toggleAlert() {
    Swal('Hello world!');
}
```

When i run it, there is an error appear in the console
![screenshot 2018-11-07 at 9 32 10 am](https://user-images.githubusercontent.com/33024986/48104937-6a27ae00-e270-11e8-87fb-3e1505a102c5.png)

After that i try to import it like this, then it works fine. 
```
import Swal from 'sweetalert2/dist/sweetalert2.js';
import 'sweetalert2/src/sweetalert2.scss';
```

Any idea what cause this problem ?

**Comment by richardhsueh** [comment]
To be more specific, I am using https://github.com/react-boilerplate/react-boilerplate as the boilerplate.

If you try to use a fresh copy of the boilerplate and install sweetalert2, it will reproduce the error.

**Comment by zenflow** [comment]
@limonte It looks like the build setup he's using is using the src and not the dist, which I didn't think anyone would be doing when I added the withNoNewKeyword trick.. I guess I neglected to notice this line: https://github.com/sweetalert2/sweetalert2/blob/dc8f8c68de2fdca68fabc7a7244d478f2177985c/package.json#L8

That trick simply won't work with the uncompiled source; an actual (un-transpiled) `class` can only be instantiated with the `new` keyword.

Since evidently noone is using the src [successfully], and since I don't see any real need to use the src rather than the dist (do you?), I think we can either remove that line or make it point to the dist, and make a patch release.

In the next major, if we can get rid of this withNoNewKeyword business (i.e. change the API from `Swal(...)` to `new Swal(...)` and `Swal.fire(...)`) then I think it would good to go back to supporting users using the uncompiled src; if they are targetting only newer browsers then they can benefit from the leaner bundle size.

**Comment by richardhsueh** [comment]
So for quick fix, can i just change 
```
"jsnext:main": "src/sweetalert2.js", 
```
to 
```
"jsnext:main": "dist/sweetalert2.all.min.js",
```

so that i can just import it like this `import Swal from 'sweetalert2';` ?

**Comment by toverux** [comment]
If you are using Weback, you can also set a resolve override for sweetalert2. Quoting https://webpack.js.org/configuration/resolve/:

--------

> A trailing $ can also be added to the given object's keys to signify an exact match:
```js
module.exports = {
  //...
  resolve: {
    alias: {
      xyz$: path.resolve(__dirname, 'path/to/file.js')
    }
  }
};
```
> which would yield these results:
```js
import Test1 from 'xyz'; // Exact match, so path/to/file.js is resolved and imported
import Test2 from 'xyz/file.js'; // Not an exact match, normal resolution takes place
```

--------

That way you can set a permanent redirect to `sweetalert2/dist/sweetalert2.all.min.js`.

**Comment by limonte** [comment]
I'd like to return to this topic with the *security* agenda.

```js
import Swal from 'sweetalert2/dist/sweetalert2.all.min.js'
```

is insecure AF. Nobody can guarantee that the minified file is the direct result of the source code minification.

Humans are sometimes doing evil (https://github.com/dominictarr/event-stream/issues/116). There are no guarantees that I will not lose my mind and inject some bitcoin-stealing shit into the minified code. Also, there are several collaborators with push access to this repo, they are also humans, also insecure. I want to protect our users from insecure imports.

Ideally, it would be great if this code would work:

```html
<script type="module">
  import Swal from './node_modules/sweetalert2/src/sweetalert2.js'
  Swal('hi')
</script>
```

Right now it throws the same exception as in the issue description:

```
withNoNewKeyword.js:11 Uncaught TypeError: Class constructor SwalWithGlobalDefaults cannot be invoked without 'new'
```

@zenflow do you maybe have any ideas on how we can achieve the same functionality and flexibility we currently have + the possibility of importing from the `src` folder? Any thoughts would be very welcome.

**Comment by zenflow** [comment]
@limonte Sorry, your comment slipped by me. 

If we are looking at supporting version 7.x after the release of 8.0, a solution might be to replace all the use of `class` syntax with old-school JS OO patterns (i.e. function MyClass () {}; MyClass.prototype.myFn = function () {}`)

Otherwise, we can simply "Drop withNoNewKeyword in coming major release" (#1368)

**Comment by limonte** [comment]
> If we are looking at supporting version 7.x after the release of 8.0, a solution might be to replace all the use of class syntax with old-school JS OO patterns (i.e. function MyClass () {}; MyClass.prototype.myFn = function () {}`)

`7.x` is good as it is.

> Otherwise, we can simply "Drop withNoNewKeyword in coming major release" (#1368)

Agree :+1:

**Comment by limonte** [comment]
Fixed in [v8.0.0](https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0), please read the release notes for the list of breaking changes in the new major release.

Live demo with ES modules: https://jsfiddle.net/bhe7vq9d/

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@8/dist/sweetalert2.css">

<script type="module">
  import Swal from 'https://cdn.jsdelivr.net/npm/sweetalert2@8/src/sweetalert2.js'
  Swal.fire('hi')
</script>
```

**Comment by tomitrescak** [comment]
This still hapents when used wtih the latest version with Vite bundler

**Comment by zenflow** [comment]
@tomitrescak This same error? Really?
![image](https://user-images.githubusercontent.com/3198597/153990214-aae211f2-f9b5-41e4-aeab-7c88648330d6.png)

**Comment by tomitrescak** [comment]
That’s correct, easy to replicate. Latest SWAL2, Vite bundler, leads to this error.

fix is usual to import from “Dist”

**Comment by zenflow** [comment]
@tomitrescak 🤔 But there's no longer any `SwalWithGlobalDefaults` class in the code... 
And the new way to instantiate a `Swal` object (`Swal.fire()`) always uses the `new` keyword... https://github.com/sweetalert2/sweetalert2/blob/master/src/staticMethods/fire.js

Can you double-check that you're using the latest sweetalert2 (version 11.4.0) and provide a stack trace? (withNoNewKeyword.js doesn't exist anymore)

**Comment by limonte** [comment]
> That’s correct, easy to replicate. Latest SWAL2, Vite bundler, leads to this error.
> 
> fix is usual to import from “Dist”

Latest SWAL2, Vite bundler, all is well: https://github.com/sweetalert2/sweetalert2-vite-demo
