### ISSUE TITLE
Add input box with HTML, label does not display

### ISSUE THREAD

**Issue by vavo-cake** [sweetalert2/sweetalert2#1324]
I used HTML to add multiple input boxes, but the label of the input box is not displayed. Checking the element finds that the label does exist. What is going on? Oh, with bootstrap3

**Comment by gverni** [comment]
Hi @vavo-cake can you provide a live example to help us debug your issue? You can remix the glitch at https://sweetalert2.glitch.me

**Comment by limonte** [comment]
Hello @vavo-cake! Could you please help me to understand the reporters' behavior and answer why didn't you follow any of the templates available in https://github.com/sweetalert2/sweetalert2/issues/new/choose ?

**Comment by limonte** [comment]
Another question, @gverni asked you to provide live demo with glitch and instead of that you just copy-pasted the code. Do you have any difficulties to create a glitch?

**Comment by limonte** [comment]
Question to @gverni : I'm a bit tired of reporters who 

- want help (our time) for free
- do not want to put their time and effort in making proper questions/feature-requests

They do respect their time and don't respect our time :/ So, should we just close such issues with a default response (GitHub's "Saved Replies" feature)? 

What do you think about that? Am I being too strict to reporters or you feel the same?

**Comment by vavo-cake** [comment]
@limonte Sorry, the current project is not deployed to the server, can not provide live demos, I will try to find out the problem myself, thank you

**Comment by gverni** [comment]
Hi @vavo-cake, you are using the `html` in the wrong way. You need to pass the html string, that in your case is given by `form[0].innerHTML`. You can have a look to the glitch here: https://sweetalert-issue1324.glitch.me/. 

> Sorry, the current project is not deployed to the server

The link I provided earlier (https://sweetalert2.glitch.me) allows to have a live server with your implementation for us to check

**Comment by gverni** [comment]
@limonte I agree with you. We had example in the past of users wasting our time. For me is still fine because it helps me learning, but I agree on the long term could not be the best. I personally am not a fan of stackoverflow because it doesn't really allow me to engage in a conversation with the user (or at least is not as effective as github issue for me). Maybe we can find a different tool to allow users to raise how to questions. I can look around and make some proposal.  What do you think?

**Comment by vavo-cake** [comment]
@gverni @limonte Thank you very much for your suggestion. I just started using github. I am not familiar with many places. I am sorry to have brought you unpleasantness. I wish you all a fortune.

**Comment by limonte** [comment]
> I personally am not a fan of stackoverflow because it doesn't really allow me to engage in a conversation with the user (or at least is not as effective as github issue for me)

True that. 

> Maybe we can find a different tool to allow users to raise how to questions. I can look around and make some proposal. What do you think?

There was Gitter back in days, I removed it because I'm personally not a fan of long conversations using human languages, I prefer code :)

Take a look at Gitter, if you like it feel free to revert https://github.com/sweetalert2/sweetalert2/commit/35b89afb71046585b9e1550d57a92c0862e2bba5

I was also thinking about recording a short (1 minute max) video on how to use glitch, it should cover:

- how to remix
- how to see the live result
- how to edit code
- how to add external scripts/styles
- how to share the result

Are you familiar with screen-recording? If not I'll handle that, if yes will you be willing to record it and upload to YouTube?

**Comment by limonte** [comment]
> @gverni @limonte Thank you very much for your suggestion. I just started using github. I am not familiar with many places. I am sorry to have brought you unpleasantness. I wish you all a fortune.

No worries, it seems that I'm not in the best mood :) We will try to improve the instructions for reporters so it will be easier for beginners to participate.

**Comment by gverni** [comment]
> There was Gitter back in days, I removed it because I'm personally not a fan of long conversations using human languages, I prefer code :)

Fair enough :-) I've never used gitter, but I'm a fan of slack, since it allows to have also chat among collaborators. But I admit that maintaining a slack community is probably a job on its own. Let me have a look to gitter and get back to you. 

> I was also thinking about recording a short (1 minute max) video on how to use glitch, it should cover:

That's a great idea. 

> Are you familiar with screen-recording? If not I'll handle that, if yes will you be willing to record it and upload to YouTube?

Yes, I'm normally using [loom](https://www.useloom.com/) for screen recording. Let me work on a video and i'll make a proposal. I can also create a short gif for people that are more familiar with sharing live example, but not with glitch itself.

**Comment by limonte** [comment]
Hello again @vavo-cake 

Just to notify you that with the latest release your original code from the issue description will work 🎉
