### ISSUE TITLE
Support use of Swal in Jest testing environment

### ISSUE THREAD

**Issue by zenflow** [sweetalert2/sweetalert2#1426]
## New feature motivation

A few days ago I was working on https://github.com/sweetalert2/sweetalert2-react-content/pull/72, and when I left it, the last commit (https://github.com/sweetalert2/sweetalert2-react-content/pull/72/commits/33fe8d658e48c466325e77dde8b33488519c8cfc) had passing tests.

When I came back to it a couple days later, the same commit had failing tests due to the v8.2.3 patch release. 

I managed to reproduce the bug in the [swal-not-resolve-in-jest-bug repo](https://github.com/sweetalert2/swal-not-resolve-in-jest-bug). You can see that [the build for the `master` branch](https://travis-ci.org/sweetalert2/swal-not-resolve-in-jest-bug/builds/497823672) (using sweetalert v8.2.2) is passing, but [the build for the `upgrade-sweetalert2-to-v8.2.3` branch](https://travis-ci.org/sweetalert2/swal-not-resolve-in-jest-bug/builds/497824375) is failing, due to the `swal` instance never resolving. (No idea why to be honest.. at first glance, [the changes from v8.2.2 to v8.2.3](https://github.com/sweetalert2/sweetalert2/compare/v8.2.2...v8.2.3) don't seem like they would cause this kind of problem)

Jest is an incredible testing tool, and it would be nice if sweetalert2 was supported [consistently] in this environment.

## New feature 

I propose to add first-class support for Jest, by doing the following things:
1. Add `check:jest` to the package scripts, with only one or two very basic tests, as "smoke testing" for the Jest environment. Fine-grained testing of functionality should continue to happen *only* in the existing karma+qunit test environment.
2. Debug and fix the above mentioned problem (reproduced in https://github.com/sweetalert2/swal-not-resolve-in-jest-bug).
3. Not strictly needed, but would make testing in Jest nicer: Check for existence of `window.scrollTo` before calling it, to avoid the need to mock it here: https://github.com/sweetalert2/swal-not-resolve-in-jest-bug/blob/f06bbd41dc51716810cd274e5e4efa7e581d5383/test.js#L4-L7

**Comment by zenflow** [comment]
Note: This is an issue with Jest v23 *and* Jest v24

**Comment by limonte** [comment]
> I managed to reproduce the bug in the [swal-not-resolve-in-jest-bug repo](https://github.com/sweetalert2/swal-not-resolve-in-jest-bug).

This issue is weird, thank you for making the repo @zenflow! 

While on the `upgrade-sweetalert2-to-v8.2.3` branch in `node_modules/sweetalert2.all.js` make this change:

```diff
-  return !!(elem && (elem.offsetWidth || elem.offsetHeight || elem.getClientRects().length));
+  return true
```

Tests are passing.

Also, they are passing with 

```js
+  return elem
```

But they are failing with 

```js
+  return elem.offsetWidth
```

> Jest is an incredible testing tool

I wonder how something can be incredible if it's failing without any sane reasons for failing and without any helping information on why and where did error occur?

This issue is most probably on jest's side and the proper place to report it is https://github.com/facebook/jest

> Add `check:jest`

I think one testing framework is enough. If someone has time and will to debug `jest`, please do so but I am against adding the complexity of dev environment to this repo because of jest's bugs.

> 3. Check for existence of `window.scrollTo` before calling it, to avoid the need to mock it here

Same here, adding code complexity and increasing the bundle size because of bugs in some testing framework doesn't sound like a good idea to me.

**Comment by limonte** [comment]
Just checked the situating with `jest` once again. They finished https://github.com/facebook/jest/issues/7807 and released https://github.com/facebook/jest/releases/tag/v24.2.0-alpha.0

The new `jest` release didn't fix the issue with SweetAlert2 >= 8.2.3

The code coverage dropped to 62%, the Travis CI dashboard is still as red as Chinese parade.

They seem to chase new technologies like TS instead of time-proven values as code coverage and the reliability of CI. Let's see if that will work well for them.

**Comment by limonte** [comment]
Reported the issue to https://github.com/facebook/jest/issues/8062

**Comment by SimenB** [comment]
>The code coverage dropped to 62%

While the code coverage certainly should be higher, it's also a bit misleading here. Jest has ~500 separate integration tests which spawns up an instance of Jest on different tests and scenarios and performs asserts on its output. This is not something that's reflected in the code coverage numbers, as those are just from unit tests. So, while I agree ~60% is lower than it could (and should) be, the code base is better covered by tests than that number indicates.

https://github.com/facebook/jest/tree/master/e2e/__tests__

>the Travis CI dashboard is still as red as the Chinese communist parade.

Note that Jest does not run tests from master in Travis (see your screenshot, the last build is 4 months ago), since travis thinks we inject some secret, turns off tty, which means all colors are borked (https://github.com/travis-ci/travis-ci/issues/7967#issuecomment-358437261). We run on PRs though to verify Jest itself works on Travis, since they are from forks they are not privileged.
We run tests for node 6, 8, 10 and 11 on Linux on circleci, node 10 for windows, mac and linux on Azure pipelines and node 10 on appveyor for windows (we'll remove that last one at some point since it's covered by azure). All of which are green (or in progress at the time of writing)

https://circleci.com/gh/facebook/jest/tree/master
https://dev.azure.com/jestjs/jest/_build?definitionId=1 (I'm not sure how to filter to just master there)

![image](https://user-images.githubusercontent.com/1404810/54027872-53a04d80-41a3-11e9-8342-f10f7ffa5464.png)

**Comment by limonte** [comment]
Thank you @SimenB I appreciate your time and the thorough explanation of why I was wrong with my doubts. 

The CI status and code coverage are the very first things I'm personally checking before even considering to use any package because there are a lot of abandoned/unmaintained projects. Using an unmaintained project is like pointing a loaded gun to your own knee, it will shoot sooner or later. 

Travis is the default CI platform for OSS so that's why I checked it instead of other CIs. I'm still not following why it's not possible to set up Travis tests on master, but that alright. Now I see that you are testing jest in other CI platforms in multiple environments.

Thank you once again for putting your time on this ticket, it always feels great to get support from a core collaborator of a product. Keep up the great work on OSS!
