### ISSUE TITLE
Why swal.fire?

### ISSUE THREAD

**Issue by WillGoldstein** [sweetalert2/sweetalert2#1438]
Just wondering, why the addition of a breaking change like .fire which seems completely unnecessary at first glance?

**Comment by limonte** [comment]
@zenflow would you mind to handle this question?

**Comment by zenflow** [comment]
We migrated the code-base to be object-oriented (i.e. we changed the `swal` function into the `Swal` class). Therefore to instantiate a swal you would need to now use the `new` keyword, e.g. `new Swal({...options})` instead of just `Swal({...options})`. 

The problem with this is that you do nothing with the result of the call (the instance) you will be violating the [eslint "no-new" rule](https://eslint.org/docs/rules/no-new), which is a common rule to be enabled, and part of [JavaScript Standard Style](https://standardjs.com/).

```js
function sayHi () {
  new Swal('Hi') // violates the eslint "no-new" rule
}
```

The `Swal.fire` static method behaves the exact same as the constructor (takes the same arguments, and returns an instance) but does not have this problem.

```js
function sayHi () {
  Swal.fire('Hi') // does not violate the eslint "no-new" rule
}
```

related: When we did most of the OO refactoring during version 7, we used a hack to allow instantiation without the `new` keyword, to maintain backwards-compatibility (i.e. you could still instantiate a swal with `Swal({...options})`) but we dropped that for version 8. See issue #1368.

**Comment by WillGoldstein** [comment]
Thanks @zenflow , appreciate the thorough explanation.

**Comment by zenflow** [comment]
@WillGoldstein please close this issue if this explains it for you, otherwise if you still have questions let me know

**Comment by zenflow** [comment]
@WillGoldstein No problem.. this should also serve other people wondering the same thing

**Comment by nafg** [comment]
To be clear, will Swal(...) work just usually have a lint error so the fire method was added, or does it not work and .fire is mandatory?

Also, why not include a (lowercase) swal method for backwards-compatibility and mark it deprecated? Or did you?

**Comment by limonte** [comment]
> To be clear, will Swal(...) work just usually have a lint error so the fire method was added, or does it not work and .fire is mandatory?

`.fire()` is mandatory.

> Also, why not include a (lowercase) swal method for backwards-compatibility and mark it deprecated? Or did you?

It is included

![image](https://user-images.githubusercontent.com/6059356/59585703-cc3f7000-90e9-11e9-8a32-60b73cbff810.png)

**Comment by nafg** [comment]
Wait, the lowercase version is a synonym for the class?

I'm confused, is it a breaking change or did you make the lowercase be
backwards-compatible?

**Comment by limonte** [comment]
The lowercase is there for backwards-compatibility, yes. But it is recommended to use `Swal` instead of `swal`.

**Comment by tomas-wrobel** [comment]
I think OOP is better.

**Comment by tomas-wrobel** [comment]
> The lowercase is there for backwards-compatibility, yes. But it is recommended to use `Swal` instead of `swal`.

`Swal` is name for class and `swal` is name for function therefore `alert`, `prompt`, `confirm` are primitive functions, and they return primitive  values. Although name `swal` is less systematic, the appearance was good anyway. The Newest updates on your website (like favicon, logo) are very good. I visit your website very often for checking updates etc.
