### ISSUE TITLE
Invalid css selector

### ISSUE THREAD

**Issue by lagden** [sweetalert2/sweetalert2#1575]
## Current behavior

https://github.com/sweetalert2/sweetalert2/blob/master/src/sweetalert2.scss#L446-L453

## Expected behavior

Nesting in something

## Demo

Output
```css
body.swal2-shown {
  overflow: hidden;
}

/* Invalid selector */
> .swal2-input,
> .swal2-file,
> .swal2-textarea,
> .swal2-select,
> .swal2-radio,
> .swal2-checkbox {
  display: none;
}
```

**Comment by limonte** [comment]
Working as expected.

**Comment by lagden** [comment]
What's it means?
Are you expecting an css error?

**Comment by bpieslak** [comment]
Hi.  I'm not sure if this is still an open issue or not, but I am encountering a similar issue.
I have an Angular project that is using sweetalert2@8.8.7

when I run `ng build --configuration=Staging`

I receive the following output:
```
WARNING in Invalid selector '> .swal2-input' at 7900:0. Ignoring.
WARNING in Invalid selector '> .swal2-file' at 7901:0. Ignoring.
WARNING in Invalid selector '> .swal2-textarea' at 7902:0. Ignoring.
WARNING in Invalid selector '> .swal2-select' at 7903:0. Ignoring.
WARNING in Invalid selector '> .swal2-radio' at 7904:0. Ignoring.
WARNING in Invalid selector '> .swal2-checkbox' at 7905:0. Ignoring.
```

I am trying to run this within an Azure DevOps CI Pipeline, and unfortunately since the Angular CLI writes warnings to STDERR, my Azure CI Pipeline fails.

I can disable this step of my Azure DevOps CI Pipeline to not fail on STDERR, but I would rather not.

In looking at the latest sweetalert2 release, it looks like the lines that @lagden identified are still present:

```
> .swal2-input,
> .swal2-file,
> .swal2-textarea,
> .swal2-select,
> .swal2-radio,
> .swal2-checkbox {
  display: none;
}
```

I'm not a CSS expert, so I don't know if those are valid CSS selectors or not.  I'm just trying to figure out why the Angular CLI is outputing warnings, and how to get around them.

Thanks!

**Comment by titobf** [comment]
I'm getting the same warning as @bpieslak on an Angular app. I ended up including "sweetalert2.all.js" (instead of "sweetalert2.js" and "sweetalert2.css") because those invalid lines are not present in this file. 
@limonte are you sure those lines must be there?

**Comment by limonte** [comment]
1. Upgrade to the latest version (8.16.2 atm)
2. I the issue still exist please report a new issue (please following the provided issue template)

**Comment by limonte** [comment]
My bad, apologies for closing the issue mistakenly. 

I'm disappointed that linters (`sass-lint` and `stylelint`) aren't handling this case. Let me see what can been done here aside fixing the actual issue. I'd like to set up linters to prevent such issues in future.

**Comment by limonte** [comment]
Filed the `stylelint` issue-report: https://github.com/stylelint/stylelint/issues/4219

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/63501467-5cc47300-c4d4-11e9-9a86-3ec5fca68c8c.png)

Sometimes my brain doesn't work s expected :laughing:

**Comment by bpieslak** [comment]
works great!
thank you for the quick fix, @limonte !

**Comment by lagden** [comment]
Good!! 👏 👏 👏

**Comment by toverux** [comment]
Ah, that's the annoying message I was getting in my Angular builds for months. I should have taken a closer look :D
