### ISSUE TITLE
ReferenceError: Can't find variable: WeakMap

### ISSUE THREAD

**Issue by cekvenich** [sweetalert2/sweetalert2#1588]
I am getting these errors at runtime at www.ubaycap.com
 with your version v8.9.0

I am using promise as you recommended.
So version 8 is less stable than 7.

**Comment by limonte** [comment]
Which browser?

**Comment by cekvenich** [comment]
The error came via monitoring app errorception and it did not say.
We just updated to v8 from v7.
Clearly, there is a polyfill missing.

**Comment by limonte** [comment]
1. when updating to a new major version, you should always read the release notes, because there are some breaking changes (that's why it's a new major).

2. WeakMap polyfill is missing in Android 4.4 native browser

3. from [v8 release notes](https://github.com/sweetalert2/sweetalert2/releases/tag/v8.0.0):

>  Breaking change # 5 - Android Browser is no longer supported
> Stick to 7.x if you need Android Browser 4.4 support.

4. If you don't need to support Android 4.4 but want to prevent those errors, include `@ungap/weakmap` polyfill

**Comment by cekvenich** [comment]
I doubt it is android 4.4, likely ie11.  That is a big download as mentioned in the discussion. And I'd have to add modernizer. We have 12 sites/app: we'll switch to Vox alert.
Thanks for the code for last few years we enjoyed using sweet alert.

**Comment by limonte** [comment]
> I doubt it is android 4.4, likely ie11.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

![image](https://user-images.githubusercontent.com/6059356/57571527-42302780-7418-11e9-93a4-97075c2231f9.png)
