### ISSUE TITLE
Support for optgroup in select input type

### ISSUE THREAD

**Issue by 4unkur** [sweetalert2/sweetalert2#1589]
Is there any support for `optgroup`'s in select input types?  
I need to show some hierarchal options in select input

**Comment by limonte** [comment]
Not at the moment, could be a good improvement though :+1:

**Comment by 4unkur** [comment]
Hi @limonte,  

Does this related to it?  
https://github.com/sweetalert2/sweetalert2/pull/549

**Comment by limonte** [comment]
Yes, but the quality of that PR wasn't good enough to be included to the codebase.

**Comment by tiagostutz** [comment]
Need some help with this? I can work on that.
I noticed that the https://github.com/sweetalert2/sweetalert2/pull/549 wasn't accepted because of some quality issues. I didn't find any guidelines on code quality or organization. Do you want to give me some advice or directions on this? Or you prefer for me to make the PR and we discuss there those details?

**Comment by limonte** [comment]
> Need some help with this? I can work on that.
> I noticed that the #549 wasn't accepted because of some quality issues. I didn't find any guidelines on code quality or organization. Do you want to give me some advice or directions on this? Or you prefer for me to make the PR and we discuss there those details?

Hey @tiagostutz!

First of all, thank you so much for becoming my sponsor via GitHub Sponsors, your support is much appreciated and it'll go a long way!

As to the code quality and contribution, there are style-guides for the library declared in https://github.com/sweetalert2/eslint-config and https://github.com/sweetalert2/stylelint-config

Aside from those, we don't have anything more detailed. The previous PR was rejected because it's missing tests and the author didn't follow the contribution guide which is described here: https://github.com/sweetalert2/sweetalert2#contributing

You can write your own solution by modifying `renderInputType.select` in `renderInput.js`. Then feel free to take a look at #549 and if you feel like some details are made better there, feel free to take them.

Let me know if you have some additional questions, I'm here to help you!

**Comment by tiagostutz** [comment]
Nice, @limonte! Thanks for the tips. 

I'm getting into the codebase right now and will make the PR asap.
