### ISSUE TITLE
SweetAlert2 does not work in Firefox extensions

### ISSUE THREAD

**Issue by alexherbo2** [sweetalert2/sweetalert2#1602]
SweetAlert2 assigns the API to `this.Sweetalert2`, but reads back the object from `window.Sweetalert2`, which – when using SweetAlert2 in Firefox extensions – leads to the following error message:

```
ReferenceError: Swal is not defined
```

I managed to make it work by replacing `window.Sweetalert2` with `this.Sweetalert2`.

A more detailed explanation can be found [here][Bugzilla#1208775].

[Bugzilla#1208775]: https://bugzilla.mozilla.org/show_bug.cgi?id=1208775

**Comment by gverni** [comment]
@alexherbo2 sorry for late reply. Can you please explain better what you changed in Swal2 code to make it work? Also if you could share the code for your extension (the parte relevant to Sweetalert) that would help to understand the issue (sorry, I didn't have time to go through the link you sent)

**Comment by alexherbo2** [comment]
I fetched the minified version of SweetAlert2, fixed it by replacing every instance of `window.Sweetalert2` with `this.Sweetalert2` and used it in a file titled `config.js`.

https://github.com/alexherbo2/firefox-configuration/blob/master/fetch
https://github.com/alexherbo2/firefox-configuration/blob/master/Makefile
https://github.com/alexherbo2/firefox-configuration/blob/master/manifest.json
https://github.com/alexherbo2/firefox-configuration/blob/master/config.js

**Comment by gverni** [comment]
@alexherbo2 I didn't forget about this issue. I haven't had a lot of time to look into that yet. As far as I understood this behavior (i.e. `this` !== `window`) is due to a Mozilla's design choice for their content script sandbox. I looked briefly at the code, and I think the `window` is added by the transpiler in the last line of the bundle, so there is nothing to be changed in the Swal2 source code to fix this.

We may create a new repo for a swal2 version for extension, but that means maintaining a new Swal2 variant for an issue that only appears with one browser (though quite popular). I want to think about that some more, if you don't mind. Feel free to send any suggestion if what I say make sense to you.
