### ISSUE TITLE
Unclickable input / select

### ISSUE THREAD

**Issue by Sharlaan** [sweetalert2/sweetalert2#1633]
## Current behavior

In a Bootstrap3* project, i'm using SWAL2 to prompt user for some vars.
The focus goes directly on first input as expected, i can tab between them, but i cannot select an input with mouse.
* i know it is old (and JQuery too ...) but no choice it is imposed by client.

## Expected behavior

As most users are more used to mouse clics than tabbing, inputs should be selectable with mouse clic.

## Live demo

I tested this code in Glitch and the inputs are perfectly clickable
```js
/* global Swal */

const cpTypes = [
  { id: 0, name: "Target 0", icon: "target0" },
  { id: 1, name: "Target 1", icon: "target1" },
  { id: 2, name: "Target 2", icon: "target2" },
  { id: 3, name: "Target 3", icon: "target3" },
  { id: 4, name: "Target 4", icon: "target4" },
  { id: 5, name: "Target 5", icon: "target5" },
  { id: 6, name: "Star", icon: "star" }
]

Swal.fire({
  html: `
    <input type="text" id="cp-name" class="swal2-input">
    <select id="cp-type" class="swal2-select">
      ${cpTypes
        .map(cpType => `<option value="${cpType.id}">${cpType.name}</option>`)
        .join()}
    </select>
    <textarea id="cp-tip" class="swal2-textarea"/>
  `,
  focusConfirm: false,
  preConfirm: () => ({
    name: document.getElementById("cp-name").value,
    cpTypeId: document.getElementById("cp-type").value,
    tip: document.getElementById("cp-tip").value
  }),
  showCancelButton: true,
//   target: this.container <= this somehow is blocking click events ??
  title: "Define a name and type for this new control point :"
}).then(({ value: { name, cpTypeId, tip = "" } }) => {
    if (name && cpTypeId) {
      Swal.fire({
        type: 'success',
        html: `
          You entered:<br>
            <strong>Name : </strong> ${name}<br>
            <strong>cpTypeId : </strong> ${cpTypeId}<br>
            <strong>Tip : </strong> ${tip}<br>
        `
      })
    }
  }
)
```

I don't understand what is preventing click events in my project ?

As a consequence, i don't have any clue what/how to test. Any insight would be appreciated.

PS: i noticed that if i comment out the `target` option, the select and other inpts become clickable again.

**Comment by gverni** [comment]
@Sharlaan can you please provide more information about the container definition and style? Is `this.container` an element with bootstrap class `container`? Can you add this and the bootstrap to the glitche example in an attempt to reproduce the issue there? 

For your information, I tried your code on a page with bootstrap v3.4.1 but I wasn't able to reproduce it.

**Comment by Sharlaan** [comment]
@gverni  thanks for your answer.

I'm indeed using BS 3.4.1 also (AdminLTE 2.4.12).

Here is a screenshot of current html
![image](https://user-images.githubusercontent.com/2692027/60170968-dcea9700-9809-11e9-9a54-ea98bec0aca0.png)
this.container = ".webgl-container"
I highlighted a tag in the tree which has `container-fluid`. That's not `container` like you asked but maybe ?

Is there a known issue with BS `container` class ?

**Comment by gverni** [comment]
Hi @Sharlaan, it's now becoming much more complicated. First of all, `vue-sweetalert2` is not maintained by this team. I'm assuming that the author is keeping up with all latest bug fixes, but I'm wondering if you discuss this issue on that repo? 

> Is there a known issue with BS container class ?

No: as I said in my previous comment I've just tried using a bootstrap `container` as target element and everything works fine. Just keep in mind that the positioning of the Swal2 inside the container is all done through CSS. So if the target container doesn't have the proper css the positioning may not work (see the requirements for this to work [here](https://github.com/sweetalert2/sweetalert2-examples/tree/master/src/parameters/toast-target)).

I don't think this can affect the click though. As far as I can see your project is _scripting rich_, so you may want to look at what's going on in the other scripts as well. From my point of view, if the basic test (i.e. _pure_ Sweetalert2 positioned in a BS container) works fine (and you verified it does), then you need to look at the interaction with the other scripts. 

I'm more than happy to look into that if at the end of your investigation it turns out to be a problem with the code in this repo.

**Comment by Sharlaan** [comment]
Ok thanks for your explanations, i understand.

EDIT: thanks for the hint, i reviewed the only other click eventListener i have in the project, which is attached to exact same container, and has `event.preventDefault()`. Since swal is async it seems to execute after my event listener, then the inner inputs/checkboxes/selects/etc don't get triggered ....

So as a solution i attached swal.target to the parent container just above this one, then the behavior is as expected pfeeeeew.... Thanks again, what a vicious one there lol !
