### ISSUE TITLE
Alert followed by toast body padding-right issue

### ISSUE THREAD

**Issue by maxstralin** [sweetalert2/sweetalert2#1640]
## Current behavior
When opening an alert, with `scrollbarPadding: true` (default), and then chaining a toast to it, the toast seems to inherit the alert's `states.previousBodyPadding`, setting a body padding even without a backdrop or removal of the scrollbar. Somewhat related to #678 

Note that this doesn't replicate if the script is triggered straight on page load, presumably because not all elements have been properly rendered yet.

Note 2: this applies when using mixins instances too:
```
const alert = Swal.mixin({
    heightAuto: false,
    buttonsStyling: false,
    customClass: {
        confirmButton: "btn btn-primary " + defaultClasses,
        cancelButton: "btn-secondary " + defaultClasses
    },
    scrollbarPadding: false
});

const toast = Swal.mixin({
    toast: true,
    type: "success",
    showConfirmButton: false,
    timer: 3000,
    position: "top"
});

export default Swal;
export { alert, toast, Swal as swal, defaultClasses }
```

```
async deleteProduct(productId) {            
    var res = await alert.fire({
        type: "warning",
        title: "Do you want to delete this?",
        customClass: {
            cancelButton: "btn-outline-primary " + defaultClasses,
            confirmButton: "btn-danger " + defaultClasses
        },
        showCancelButton: true,
        cancelButtonText: "No, don't delete",
        confirmButtonText: "Yes, delete",
        reverseButtons: true,
        focusCancel: true
    });

    if (res.value === true) {
        await api.delete("products/" + productId);
        var index = this.products.findIndex(a => a.productId == productId);
        this.$delete(this.products, index);
        toast.fire({
            title: "Deleted",
            timer: 3000,
    });
    }
}
```

## Expected behavior
Alert should restore the body's padding and the toast shouldn't set any body padding.

## Live demo 
https://dolomite-saver.glitch.me/
https://jsfiddle.net/n1dbypfa/

**Comment by gverni** [comment]
Thanks @maxstralin, the behaviour you reported is due to the fact that when the modal closes, it registers for the _end of the closure animation_ event (i.e. `animationEndEvent` in Swal2 code). Only when this event happens, then the status of the page is reset, and this includes restoring the original body padding. 

If another Swal2 (either modal or toast) is executed before the closure animation of the first modal is over, then the `animationEndEvent` is not triggered for the first Swal2. 

If I understood correctly your issue, you should not see this behaviour if you set `animation: false` on the first modal. 

Let me look into that and come up with a proposal.

**Comment by maxstralin** [comment]
@gverni Indeed, setting `animation: false` on the alert removes the issue! 
Do you need any more information from me or are you happy to debug this with the information provided?

**Comment by gverni** [comment]
@maxstralin no more information thanks! I tried a couple of solutions but they are breaking other use cases. I need to dig more into that.

**Comment by gverni** [comment]
@limonte in #1570 you added: 

https://github.com/sweetalert2/sweetalert2/blob/78920dcba676e2325f7ea27ec0756eaf7508d42a/src/instanceMethods/close.js#L59-L60

This gets executed only when there is an animation (since it's in `swalCloseEventFinished`). Is there any specific reason why this is not executed when there is no animation? In fact when there is no animation, the following code gets executed: 

https://github.com/sweetalert2/sweetalert2/blob/78920dcba676e2325f7ea27ec0756eaf7508d42a/src/instanceMethods/close.js#L86-L89

**Comment by limonte** [comment]
@gverni no specific reason for that, most probably my mistake, feel free to change

**Comment by gverni** [comment]
Thanks @limonte. A couple of more questions (they are all related to the fix I'm coding for this issue): 

* Are instance methods (such as `getInput()`) supposed to work in the `then`?
* If a Swal is fired inside an `onClose` function, what are the instance methods called in the the `then` of the main Swal supposed to refer to? For example the following code: 

```javascript
  Swal.fire({
    input: 'text',
    inputClass: 'outer-swal',
    onClose: () => {
      Swal.fire({
        input: 'text',
        inputClass: 'on-close-swal'
      })
    }
  }).then((result) => {
    console.log(Swal.getInput().classList)
  })
```
Currently is printing: 

```
["swal2-input", "on-close-swal", value: "swal2-input on-close-swal"]
```
So it's clearly referring to the Swal fired in the `onClose`. Is this the expected behaviour?

**Comment by limonte** [comment]
> Are instance methods (such as getInput()) supposed to work in the then?

Yes.

> So it's clearly referring to the Swal fired in the onClose. Is this the expected behaviour?

Yes, because `onClose` is executed before `then`. If users want to execute something after `then`, there's `onAfterClose`.

**Comment by gverni** [comment]
Thanks @limonte! 

> Are instance methods (such as getInput()) supposed to work in the then?
> Yes.

Currently this is working for the first ~150ms (i.e. animation duration). The following code: 

```javascript
  Swal.fire({
    input: 'text',
    inputClass: 'outer-swal',
  }).then((result) => {
    setTimeout(() => {
      console.log(Swal.getInput().classList)
    },160)
  })
```

causes the following error in console: 

```
sweetalert2.js:1644 Uncaught TypeError: Cannot read property 'content' of undefined
    at SweetAlert.getInput$1 [as getInput] (sweetalert2.js:1644)
    at Function.SweetAlert.<computed> [as getInput] (sweetalert2.js:2779)
    at sandbox.html:32
```

I think the reason is that after the animation is finished, we call the `unsetWeakMap()`. And that makes the instance methods not accessible. I'm going to fix this as well then because to me it's a bug.

**Comment by maxstralin** [comment]
Not sure if this is related to anything but the example as provided above  (`async deleteProduct()`), I seemed to have some occurrences where if I awaited the first alert but didn't await the toast (just fire 'n forget), it started spitting errors about not being able to read property of undefined, a bit like you described above. It stopped by itself so didn't include it in the report but it may be that it's a timing issue waiting to happen then.

Just thought I'd add it since I saw the comment above but don't have any good information on how to replicate it more than that it seemed to happen in an async function if not awaiting a second swal after awaiting the first swal. Chaining it with a `.then()` seemed to work too.

**Comment by gverni** [comment]
Thanks @maxstralin. If you are able to replicate it consistently, that would help me for writing test cases. Don't worry too much if you can't reproduce it (unless you reproduce it also with `animation: false`). For the moment I've got enough test cases and I think I identified where the issue is. I'll ask you to try the fix once I have it.

**Comment by gverni** [comment]
@maxstralin the fix is now merged. Could you double check it with your code as well?
