### ISSUE TITLE
After v8.13.2, Angular not becoming "stable" after closing Swal.

### ISSUE THREAD

**Issue by hensleyrob** [sweetalert2/sweetalert2#1654]
## Current behavior

After v8.13.2, in an Angular application (tested in Angular 7.2 nd 8.0), fire a Swal and close it. In browser console run...

window.getAllAngularTestabilities()[0].isStable();

This will report false until the DISPOSE_SWAL_TIMEOUT is reached.

## Expected behavior

Once the Swal is closed, isStable() should return true. This is currently breaking our selenium tests as we don't proceed with a lot of actions until Angular reports back "stable."

**Comment by gverni** [comment]
I'm not an expert of selenium / angular, so I'm not sure what the isStable() does. @hensleyrob 
in 8.13.2 we added a timeout to dispose of some of the Swal internal objects to allow GC to remove  them. Previously those internal objects were removed within the first ~150ms. 

@limonte we can make `DISPOSE_SWAL_TIMEOUT` a Swal configuration instead of a constant. And reduce the default value (currently it's set to 36000 ms). I can work on that if you like the proposal.

**Comment by limonte** [comment]
> @limonte we can make DISPOSE_SWAL_TIMEOUT a Swal configuration instead of a constant. And reduce the default value (currently it's set to 36000 ms). I can work on that if you like the proposal.

Why `DISPOSE_SWAL_TIMEOUT` is 36000 ms at the first place?

**Comment by gverni** [comment]
The idea behind that was to make it long enough to avoid disposing of those object too quickly (since they are needed if you want to access the Swal after it closes) but not too long to go beyond the lifetime of a page. But I agree it's possibly too high. 

On the other hand this is a typical _how long is a piece of string_ problem. It all depends on how much code gets executed in the `then` that still need to access the Swal properties: 500ms? 1sec?

**Comment by limonte** [comment]
Now I have the question why do we have `DISPOSE_SWAL_TIMEOUT` at the first place :) @gverni please review #1655 and let me know if I'm missing something because all tests are passing after removing `DISPOSE_SWAL_TIMEOUT`.

**Comment by hensleyrob** [comment]
I can confirm this is fixed in 8.13.6, thanks for the quick turnaround!

**Comment by limonte** [comment]
Thank you @hensleyrob  for reporting the issue and confirming the fix!
