### ISSUE TITLE
Types: DismissReason enum

### ISSUE THREAD

**Issue by Basaingeal** [sweetalert2/sweetalert2#1712]
## Current behavior

When a SweetAlertResult is returned with a DismissReason, the dismiss reason is a string.
However, the Swal.DismissReason type is a standard typescript enum, implying that it will be a number

## Expected behavior

The Swal.DismissReason enum declaration would be a string enum
```ts
enum DismissReason {
  cancel = 'cancel',
  backdrop = 'backdrop',
  close = 'close',
  esc = 'esc',
  timer = 'timer'
}
```

## Live demo 
https://tasteful-spectrum.glitch.me

**Comment by toverux** [comment]
Yes, but it is not possible to declare enum values in a `.d.ts` file.
However, this should not be a problem. Instead of comparing like this `dismiss == 'cancel'` for example, use the enum : `dismiss == Swal.DismissReason.cancel`. There, TypeScript shouldn't complain.
If you have a better idea, that works in the `.d.ts` while keeping the enum, please let us know.

**Comment by Basaingeal** [comment]
Would not `dismiss == Swal.DismissReason.cancel` be transpiled to `dismiss == 0` which would evaluate to false? I might be missing something about the transpilation process, but that's my impression from reading the [enum documentation](https://www.typescriptlang.org/docs/handbook/enums.html)

Also, I don't mean to doubt you, but just changing the enum to a string enum in the sweetalert2.d.ts seems to work fine for me. Is there information somewhere that I could see that indicated that string enums don't work in declaration files?

**Comment by toverux** [comment]
> Would not dismiss == Swal.DismissReason.cancel be transpiled to dismiss == 0 which would evaluate to false?

No, don't worry, `.d.ts` file *never* have any kind of influence on the emitted code. The enum itself and its values are always coming from the SweetAlert source, that is JavaScript.
A `.d.ts` file cannot bear any actual value that can be used at runtime. That's pure types.

> Also, I don't mean to doubt you, but just changing the enum to a string enum in the sweetalert2.d.ts seems to work fine for me.

That is possible, however (that'd still be types... no matter what values you put in the enum members, at runtime that'll still be what SweetAlert declared).
I said that by memory, so I'm not sure, you may be right. In that case that would fix comparison with simple strings.

**Comment by toverux** [comment]
Just tried, apparently that's still not possible!

![image](https://user-images.githubusercontent.com/1343250/63295002-f40aaa00-c2cb-11e9-8ef2-87347d33560b.png)

And that's possibly by design. After all, it is safer to use the enum rather than the actual values directly. I think TypeScript could support that, but maybe they decided to discourage it?

**Comment by Basaingeal** [comment]
Alright. Thanks for the information. I ran some tests using the declaration file, and you're right, the evaluations work out.

I'm working on a library that needs to serialize these results to JSON strings, so some of my type conversions were not going as expected, but I think I can sort it out now based on the information provided.

Thank you.
