### ISSUE TITLE
Draggable

### ISSUE THREAD

**Issue by pjebs** [sweetalert2/sweetalert2#1722]
For all clickable/focussable elements including buttons, can you please add this css:

`-webkit-app-region: no-drag;`

**Comment by limonte** [comment]
Why?

**Comment by pjebs** [comment]
All will be explained in a secret project that will be open sourced soon. ;-)


 But does making the change have any adverse impacts on your project?

**Comment by toverux** [comment]
sweetalert2 is installed 107 097 times _a week_.
Should we add this line, for no apparent reason, in a package that is installed one hundred thousand times a week?
I don't think so.
Please demonstrate how this will add value for our customers, regardless of the existence of your project.
Otherwise, please instead override the sweetalert2 CSS classes yourself to add this to your project.

**Comment by limonte** [comment]
Agree with @toverux, let's not play secret projects and Sherlock Holmes here :)

Please use the `customClass` parameter https://sweetalert2.github.io/#custom-class

```css
.no-drag {
  -webkit-app-region: no-drag;
}
```

```js
Swal.fire({
  ...
  customClass: {
    closeButton: 'no-drag',
    confirmButton: 'no-drag',
    cancelButton: 'no-drag',
  }
})
```

**Comment by NadavRothVerte** [comment]
@toverux 
actually i want to make swal2 draggable so it would be nice if the option will be there, make it more generic.
