### ISSUE TITLE
insertQueueStep isn't honoring mixing parameters

### ISSUE THREAD

**Issue by mkg20001** [sweetalert2/sweetalert2#1746]
## Current behavior

After confirming the first dialog, a second, normal success dialog appears

## Expected behavior

It should use the parameters from the mixin for the second dialog which would make it show a toast

## Live demo 

https://glitch.com/~boggy-gorgonzola

```js
const Toast = window.swal.mixin({
  toast: true,
  position: 'top-end',
  showConfirmButton: false,
  timer: 5000
})
Swal.queue([{
  title: 'confirm me',
  preConfirm: () => {
    Toast.insertQueueStep({type: 'success', title: 'well done'})
  }
}])
```

**Comment by gverni** [comment]
That's an interesting experiment @mkg20001. As a matter of fact, `insertQueueStep()` is a _static_ method of `Swal` (i.e. it doesn't apply to the specific instance it's called upon). Since you are calling it from within an instance of `Swal` (and not of `Toast`) then the argument it's applied to `Swal` (i.e. `Toast` mixin is ignored). Does it make sense for you? 

Unless the `insertQueueStep()` is changed to an instance method, I don't think this is easily achievable. @limonte , @zenflow  do you agree with this statement? 

There's obviously ways around that without using `mixin` but maintaining a similar structure to your example, such as (using the spread operator):

```javascript
const Toast = {
  toast: true,
  position: 'top-end',
  showConfirmButton: false,
  timer: 5000
}
Swal.queue([{
  toast: false,
  title: 'confirm me',
  position: 'center',
  showConfirmButton: true,
  preConfirm: () => {
    Swal.insertQueueStep({...Toast, type: 'success', text: 'well done'})
  }
}]) 
```

**Comment by mkg20001** [comment]
Understand. Maybe it could be wrapped by the mixin? So it would instead be a function that does what your example described?

**Comment by gverni** [comment]
Could you elaborate on that @mkg20001? What you mean with _wrapped by the mixin_?

**Comment by mkg20001** [comment]
I mean something like returning a new object with a wrapped function

```js
mixin = (mixed) => {
  Toast = Swal.mixin(mixed)
  Toast.insertQueueStep = (args) => Swal.insertQueueStep({ ...mixed, args })
  return Toast
}
```

**Comment by gverni** [comment]
@mkg20001 if I understood correctly your suggestion, that would mean having a different implementation for the mixin for the queues. That is not possible with the current architecture, since the queue is _just_ an implementation on top of a single Swal, and it's the key to making Swal so flexible. Until `insertQueueStep()` is changed to an instance method, I'n afraid there is nothing much we can do.
