### ISSUE TITLE
Provide the API method for swal.getContent().querySelector('#swal2-content')

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1809]
## New feature motivation

In both React and Angular integrations there's `swal.getContent().querySelector('#swal2-content')`:

- https://github.com/sweetalert2/sweetalert2-react-content/blob/3101894feffa57153a88c4657a6ec738a212f75b/src/mounts.js#L8
- https://github.com/sweetalert2/ngx-sweetalert2/blob/master/projects/ngx-sweetalert2/src/lib/swal-portal-targets.service.ts#L38

That's not good because an integration shouldn't rely on internal selectors like `#swal2-content` as they are subject to change without any notice.

## New feature description

Provide a getter, `Swal.get<¯\_(ツ)_/¯>`. I'm struggling with a name for the getter. Does someone maybe have a good idea how to name `#swal2-content` which is the DOM node where `html/text` parameter would be rendered to.

@zenflow @toverux any input from you guys is very welcome.

**Comment by zenflow** [comment]
In sweetalert2-react-content I have a test helper called `getSwalContentContent`, which as a method of `Swal` would be `Swal.getContentContent()`.

I think that it's accurate but not beautiful, because it reflects that we have 2 different `<div>`s (one contained inside the other) both with the label of "swal2-content":
![image](https://user-images.githubusercontent.com/3198597/68773938-ac768e80-062c-11ea-95b9-9ebfe76e482f.png)

Is there any way we could improve the semantics around "container", "content", "content content" without making breaking changes? I.e. not change `id="swal2-content"` to `class="swal2-text"` or something like that

**Comment by limonte** [comment]
> Is there any way we could improve the semantics around "container"

I was thinking about that keyword as well, `.getHtmlContainer()`. In that case, the classname would be `swal2-html-container`.

> I.e. not change id="swal2-content" to class="swal2-text" or something like that

We can have `.swal2-html-container` alogn with `#swal2-content`. The API method will be using the calassname, and the id will be there for compatibility with projects/plugins which are relying on it already.
