### ISSUE TITLE
Alert Stays On Screen After Clicking OK. 9.4.3

### ISSUE THREAD

**Issue by wilecoyte78** [sweetalert2/sweetalert2#1841]
+ sweetalert2@9.4.3

The popup shows fine and when I click close the popup stays on the screen:

Before clicking OK:

http://x-v.it/qxv5cl

After clicking OK:

http://x-v.it/frp51k

I do not know why the alert is staying on the screen after clicking OK. The overlay does disappear.

	Swal.fire({
		icon: 'error',
		title: 'Error!',
		html: 'The response is no longer valid: either is too old or has been used previously<br>Invalid Full Name<br>Invalid Phone Number<br>Invalid Email Address!<br>',
		animation: false, customClass: 'animated shake'}).then(( result ) => {
		if( result.value ) {
			// Do something			
		} else {
			
		}
	});

**Comment by wilecoyte78** [comment]
I just did this for now:

	Swal.fire({
		icon: 'error',
		title: 'Error!',
		html: 'The response is no longer valid: either is too old or has been used previously<br>Invalid Full Name<br>Invalid Phone Number<br>Invalid Email Address!<br>',
		animation: false, customClass: 'animated shake'}).then(( result ) => {
		if( result.value ) {
			// Do something
			$('.swal2-container').remove();
		} else {
			
		}
	});

**Comment by limonte** [comment]
The `animation` parameter has been deprecated in `v9.0.0`. Please use the `showClass` parameter instead of `animation: false, customClass: 'animated shake'`:

Swal.fire({
  ...
  showClass: {
    popup: 'animated shake'
  }
  ...
})

And don't forget to read the release notes when upgrading any library to a new major release: https://github.com/sweetalert2/sweetalert2/releases/tag/v9.0.0
