### ISSUE TITLE
Can't update "allowOutsideClick" parameter

### ISSUE THREAD

**Issue by AlbertMN** [sweetalert2/sweetalert2#1866]
## Current behavior
When trying to set the `allowOutsideClick` parameter to `true` or `false` in `Swal.update({ ... })`, it gives this warning;

```
SweetAlert2: Invalid parameter to update: "allowOutsideClick". Updatable params are listed here: https://github.com/sweetalert2/sweetalert2/blob/master/src/utils/params.js
```

The document it refers to does include the `allowOutsideClick` parameter, so it should be update-able through the `update` method.

## Expected behavior
It should be able to be updated.

If you just set the parameter to `allowOutsideClick: () => CanClosePrintSwal(),`, it will be dynamic and you can just make `CanClosePrintSwal()` return a change-able bool, but took me some time to come to this conclusion, and seeing that (from what I can gather) it isn't documented anywhere that you can't change `allowOutsideClick` through the update method, I'd consider this a bug.

## Live demo 
https://codepen.io/iversen/pen/bGNjQoj

**Comment by AlbertMN** [comment]
Thanks for the super fast response (and fix)! Love this library - been using it for years _(best regards, your first Patreon back in the old days :) )_

**Comment by limonte** [comment]
> Thanks for the super fast response (and fix)! Love this library - been using it for years _(best regards, your first Patreon back in the old days :) )_

Hello Albert, I remember you from Patreon!

You're very welcome! Thank you for putting the effort into the proper issue-report.
I left Patreon a while ago because they decided to bring censorship between creators and patrons, which isn't acceptable for me personally. 

Nowadays GitHub is providing an outstanding alternative for Patreon: https://github.com/sponsors/limonte To supercharge community funding, GitHub [will match](https://help.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/about-github-sponsors#about-the-github-sponsors-matching-fund) all contribution from patrons.
