### ISSUE TITLE
rollup swal: require('sweetalert2') no css

### ISSUE THREAD

**Issue by pjebs** [sweetalert2/sweetalert2#1869]
When I `require('sweetalert2')`, and then bundle with rollup.js, sweetalert appears to work but it doesn't have the css.

Is this a bug? Or did I do something wrong?

**Comment by limonte** [comment]
That's because Rollup prioritize `package.json`'s fields this way:

-    `module` (if enabled)
-    `jsnext:main` (if enabled)
-    `main`

Source: https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L59

In `sweetalert2`'s `package.json` the `module` field points to the unstyled file `src/sweetalert2.js`. That's made in order for SweetAlert2 to work with ES Modules in a browser, see the demo project: https://github.com/sweetalert2/sweetalert2-es-module-demo

---

In order to make in work with Rollup, you'll need to change `require('sweetalert2')` to `require('sweetalert2/dist/sweetalert2.all.js')`
