### ISSUE TITLE
SWAL2 8.19.0 to 9.7.2 - Icon Issue

### ISSUE THREAD

**Issue by pierreminiggio** [sweetalert2/sweetalert2#1885]
Hello, just updated Swal from 8.19.0 to 9.7.2.
I changed all my "type" option to "icon".
But now icons look buggy. (I use "success", "warning", and "info" in my app, and both "info" and "warning" look buggy).
Was there something else I was supposed to do to update properly ? Or is it an issue with the library ? 

https://www.youtube.com/watch?v=JBW09WMcRGQ

**Comment by pierreminiggio** [comment]
Okey. Found my problem.
One of my package was still looking for the 8.19.0 version while my main project had the 9.7.2 version.
So I had both of these version listed in my lock file.

Updated my package's package.json so it gets the updated version as well, and everything went back in order.

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/74093331-3bcef900-4ad9-11ea-9bab-d32c03c1a843.png)

Using stars instead of semver ranges is the right way to shought your knees :)

Recommendation:

```
"sweetalert2": "^9.0.0",
```

**Comment by pierreminiggio** [comment]
Just wanted to update everything to the latest versions.
So I replaced all the ranges for stars, then replaced with new ranges again.
How are we supposed to update to the next major on a library if we want to? Is there a better way to do it ?

**Comment by toverux** [comment]
> How are we supposed to update to the next major on a library if we want to? Is there a better way to do it ?

If you are using [yarn](https://yarnpkg.com/) (otherwise I can only recommend it to you) instead of npm, you may use `yarn upgrade-interactive --latest` (`--latest` is to search for versions not currently included in your semver ranges), and select the packages to upgrade interactively.

There are plenty of other methods including with npm but this one is by far the most secure and you'll know what you're doing.
