### ISSUE TITLE
Cant scroll / zoom in IOS

### ISSUE THREAD

**Issue by SirApple31** [sweetalert2/sweetalert2#1891]
On the latest version of IOS, i cannot zoom out or scroll. Event on the exemples on github, but I can on android.

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

**Comment by grutherford** [comment]
> On the latest version of IOS, i cannot zoom out or scroll. Event on the exemples on github, but I can on android.

I can confirm this is still a bug

**Comment by limonte** [comment]
> 
> 
> > On the latest version of IOS, i cannot zoom out or scroll. Event on the exemples on github, but I can on android.
> 
> I can confirm this is still a bug

I can confirm that the properly reported issue is still required.

**Comment by ropeko** [comment]
The issue still exists.
Here is a screenshot: 
![image0](https://user-images.githubusercontent.com/6683990/98444654-2c85e600-2113-11eb-80f4-6d4eec82e878.png)

Now I would like to zoom out so that the buttons of the alert are visible. But I can not zoom anymore as soon as an alert is displayed. Also moving the screen (scrolling on mobile) is not working.

My code:
`
    Swal.fire({
        title: 'Are you sure want to reset the current board? To only change display size and grid lines use "Change grid" button',
        html: '<h4 style="color:red;">You won\'t be able to revert this!</h4>',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, Reset it!'
    })
`

iOS version: 14.1 (but seems to be an issue on older iOS version as well according to above comments)

Let me know if you need more information.
