### ISSUE TITLE
Change the way detect nodejs environment

### ISSUE THREAD

**Issue by ysmoradi** [sweetalert2/sweetalert2#1922]
Can we use

```js
  var isNodeEnv = function isNodeEnv() {
    return typeof global != 'undefined';
  };
```

instead of

```js
  var isNodeEnv = function isNodeEnv() {
    return typeof window === 'undefined' || typeof document === 'undefined';
  };
```

To make angular universal works with some libraries, I've to provide a shim for window and document objects. If we use global object which is node-specific, we can address the issues better.

Thanks for the fantastic library.

**Comment by limonte** [comment]
Thank you @toverux, now I noticed this handy button :)

![image](https://user-images.githubusercontent.com/6059356/77068970-33c77a80-69f0-11ea-9808-a9263db41aad.png)

**Comment by limonte** [comment]
Reopening the issue because unfortunately, I had to undo this change, see details in #1927

**Comment by ysmoradi** [comment]
I understand, now, what's the next plan! ;D

**Comment by limonte** [comment]
For now, I don't have any.

**Comment by zenflow** [comment]
@ysmoradi 

What exact problem do you run into using this library with angular universal (without shimming `window` and `document`)?

This library won't work on server side in any case, because this library works directly with the DOM. You can import/require the module server-side, but that is the full extent of support for SSR/universal apps; you can not actually render an alert server-side (unless it is via some kind of global virtual `document` object, which doesn't seem to be the case with Angular universal since you mentioned having to shim `document`).

Did you have a chance to try things out with your suggested change? If not, can you please try with version 9.10.3? Did everything work as you expected/desired?

It seems that checking for existence of `window` & `document` is appropriate, since we actually don't care if we are running in nodejs or whatever environment; we only care if we have the needed `window` & `document` objects to work with. The check is there so that developers get a clear & understandable error message, instead of a more confusing one when this library tries to interact with a non-existent `document` object.

**Comment by zenflow** [comment]
Basically, I think the error "SweetAlert2 requires document to initialize" was correct in the first place. Just preventing that error from happening will not change the fact that "SweetAlert2 requires document to initialize".
