### ISSUE TITLE
Separate loader and confirm button

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#1942]
## Current behavior

Currently, when in the loading state, the confirm button becomes disabled and turns into loader. That poor decision was made by me long time ago when I wasn't paying too much attention to customization and theming.

## Expected behavior

Loader should be the separated DOM node with its own styles so users will be able to easily customize it without breaking the confirm button. The oldest opened issue of this repo #534 will be resolved by this.

With the current solution users have to use workarounds like this one #1941

**Comment by gverni** [comment]
@limonte I think this introduces a side issue. The buttons remain disabled after `Swal.showValidationMessage()` is called. To test it use: 

* `yarn start` (using default `sandbox.html`) 
* Do not write anything in the input 
* Click the ok button 
* Both ok and cancel buttons are greyed out and they are not re-enabled when typing 

Is this an expected behavior introduced by this braking change?

**Comment by limonte** [comment]
> 
> 
> @limonte I think this introduces a side issue. The buttons remain disabled after `Swal.showValidationMessage()` is called. To test it use:
> 
>     * `yarn start` (using default `sandbox.html`)
> 
>     * Do not write anything in the input
> 
>     * Click the ok button
> 
>     * Both ok and cancel buttons are greyed out and they are not re-enabled when typing
> 
> 
> Is this an expected behavior introduced by this braking change?

I'm aware of that issue, it'll be fixed before the release, thanks for noticing it!

**Comment by gverni** [comment]
> I'm aware of that issue, it'll be fixed before the release, thanks for noticing it!

Great thanks! I just stumbled on it while testing the other PR and wanted to make sure was tracked somewhere ;-)
