### ISSUE TITLE
Support ObservableLike

### ISSUE THREAD

**Issue by dev054** [sweetalert2/sweetalert2#1982]
## New feature motivation
I'm currently working with Angular projects and whenever we use the `preConfirm` option we have to convert the `Observable` that usually comes from an API call to a `Promise` calling `.toPromise()`. It would be great if _sweetalert2_ supported `ObservableLike` natively.

## New feature implementation
 I'd imagine that it could check if the parameter received in `preConfirm` has the method `toPromise`, then call it and do everything as it's today, something like this:

Today's code:

https://github.com/sweetalert2/sweetalert2/blob/51aca13ddf8ed7ddc2f8e0cd88e844cce04ae8bb/src/instanceMethods/buttons-handlers.js#L57

"Proposal" code:

```ts
const preConfirmPromise = Promise.resolve().then(() => {
  const result = innerParams.preConfirm(value, innerParams.validationMessage)
    
  // return result.toPromise && result.toPromise() || result
  // or

  return 'toPromise' in result ? result.toPromise() : result
})
```

**Comment by limonte** [comment]
No, thanks. `ObservableLike` seems to be the part of Angular and SweetAlert2 shouldn't take the framework-related things into consideration.

**Comment by zenflow** [comment]
@limonte Actually Observables are a generally useful programming construct used in a variety of frameworks, libraries, apps. There's also lot of different libraries that implement it and provide tools besides RxJS (the library Angular uses), like [kefir](https://kefirjs.github.io/kefir/) and [zen-observable](https://github.com/zenparsing/zen-observable). They are kinda similar to Promises, because they represent async/future value(s), but different, because they can have more than one (or no) future values. There's [a proposal to add it to the language](https://github.com/tc39/proposal-observable) which is taking forever to pass through, but it seems to be expected to happen eventually. Regardless of that it's a useful construct being used in the wild already.

My only concern is that there is no `toPromise` method on the standard/generic observable. It's not included in the proposed spec, and it's not included in simple/barebones implementations like zen-observable. Though it is included in RxJS & kefir (as a small sample).

But I don't see the harm of adding the convenience of automatically converting `ObservableLike`s (or rather, any object implementing `toPromise()`) to `Promise`s. Is there any downside to this @limonte ?

**Comment by limonte** [comment]
Thank you for your input @zenflow! Aside from a slightly bigger codebase, I do not have any other downsides.

@dev054 would you be willing to create a PR with the code proposed in the feature-request description?

**Comment by zenflow** [comment]
An important issue with the proposed code: If you check the documentation for `preConfirm` ([here](https://sweetalert2.github.io/#configuration)) you see that it's return value can be a lot of things that would cause errors this code. For example, if the user's `preConfirm` function returned `false`, it would throw a `TypeError: Cannot use 'in' operator to search for 'toPromise' in false`. I suggest replacing `'toPromise' in result` with `typeof result === 'object' && typeof result.toPromise === 'function'`.

Will types be updated? In this area we should keep in mind that we are not actually accepting/expecting an `Observable` or `ObservableLike` for `preConfirm` return values, because Observables don't necessarily have a `.toPromise()` method. What we *are* accepting/expecting is any object with a `.toPromise()` method. That just happens to include some types of observables. 😉 

If we do this with the `preConfirm` option, should we do this to the rest of the options that currently take a Promise or Promise-returning function? Those options are `inputValue`, `inputOptions` & `inputValidator`. This would make a nice consistent API, and be the way I would  probably want it if I was using Observables and Swal together. @dev054 Would you agree? Would it be desirable to have the same convenience with these other options if you were using them? I assume that you were just unaware of (not using) the other options. The title of this issue is an unqualified "Support ObservableLike", not "Support ObservableLike for preConfirm option".
