### ISSUE TITLE
RTL range input

### ISSUE THREAD

**Issue by maaaom** [sweetalert2/sweetalert2#2008]
Hi,

When the direction is RTL, the range input was not in RTL direction, how I can make it in RTL direction ?!

**Comment by limonte** [comment]
Please follow the issue template when reporting issues.

![image](https://user-images.githubusercontent.com/6059356/66860984-cc1b8800-ef96-11e9-8f5f-107553d403bf.png)

**Comment by zenflow** [comment]
@limonte Github actions! Sounds like a fun job. I might take a go at it if you don't want to spend the time on it but you will review the code. Open?

**Comment by limonte** [comment]
With Saved Replies it takes 5 second to me to reply with a template and close the issue. I'll need to open the issue with or without robot, so the amount of potentially saved time here will be too insignificant to introduce the new code.

**Comment by zenflow** [comment]
Oh, ok, I sensed that it might be too much because #2007 was closed without comment. I just really love the power of Actions and was looking for something good to do with it. I am curious though what your reason for dismissing #2007 was though and how you know it's not an upgrade problem that users are facing.

**Comment by limonte** [comment]
#2007 was very poorly reported and `Buffer` isn't used in SweetAlert's codebase.
