### ISSUE TITLE
The URL validator doesn't match certain valid TLDs

### ISSUE THREAD

**Issue by pitust** [sweetalert2/sweetalert2#2011]
## Current behavior

http://g.co is not recognized as a valid URL

## Expected behavior

http://g.co is recognized as a valid URL. Also, all of these are valid (and not accepted):
 - ftp://g.co/file/over/ftp
 - http://[/root/unix/domain/socket]/file/over/unix/domain/socket
 - ws://locahost/a/web/socket

## Live demo

https://codepen.io/Piott/pen/OJMZpom

**Comment by limonte** [comment]
Thank you for reporting this issue @pitust!

Unfortunately, your PR can't be the solution here because we have to support IE11.

Yould anyone like to check if the existed regex could be improved to support

- http://g.co
- ftp://g.co/file/over/ftp
- http://[/root/unix/domain/socket]/file/over/unix/domain/socket
- ws://locahost/a/web/socket

@gverni @tiagostutz or anyone else ?

**Comment by pitust** [comment]
Maybe we could revert to the regex if in IE11

**Comment by limonte** [comment]
> 
> 
> Maybe we could revert to the regex if in IE11

In that case the same validator would work differently for different browsers. Not sure if that's better than the incomplete validation which is consistent across all browsers. Let me think on this.

**Comment by limonte** [comment]
BTW

```
new URL('http://[/root/unix/domain/socket]/file/over/unix/domain/socket')
```

throws `Uncaught TypeError: URL constructor: http://[/root/unix/domain/socket]/file/over/unix/domain/socket is not a valid URL.`

**Comment by limonte** [comment]
I fixed the regex to support `https://g.co`, other urls from the issue description (ftp, ws, /root/unix) are still not supported and since there's no universal cross-browser solition I'm closing this issue. 

Developers can always override the default validator if they want to support unusual urls.
