### ISSUE TITLE
Modal does not appear in Google Maps fullscreen mode until you exit fullscreen

### ISSUE THREAD

**Issue by produktive** [sweetalert2/sweetalert2#2025]
I have a button on a Google maps canvas that opens a Swalert. In all devices except iOS, there is a fullscreen button on Google maps. The modal displays fine when not in fullscreen. If in fullscreen and you click the button, the Swalert does not appear. Once you exit fullscreen, only then do you see the modal. Can be tested on [https://bbq.crabdance.com/cca/](https://bbq.crabdance.com/cca/). Click the "?" button normally, then try in fullscreen (the box icon in top right).

**Comment by limonte** [comment]
Browsers set `z-index` of fullscreened elements to `2147483647` (the largest 32-bit signed number). 

In order to make sweetalert2 visible you have to move it to the fullscreened element by using the `target` parameter:

```js
Swal.fire({
  target: '#fullscreened-element'
})
```

![DrJYPTHNyp](https://user-images.githubusercontent.com/6059356/88720125-07a1d000-d12d-11ea-9ac0-f17a91f9f6a4.gif)

**Comment by TH3AL3X** [comment]
`window.onload = function () {
    // Change fullscreen to the id wathever you want, for do the target thing
    $("#map div:first").attr('id','fullscreen');
}`
