### ISSUE TITLE
allowOutsideClick with long dropdown

### ISSUE THREAD

**Issue by bytestream** [sweetalert2/sweetalert2#2154]
## Current behavior

I have a long dropdown menu which is enhanced by a dropdown library: https://github.com/selectize/selectize.js (similar to Select2)

If you click on options which overflow outside of the modal then the modal closes. If you click on options within the modal, then they're selected as you'd expect. For example:
* Option 2 can be selected OK
* Option 6 closes the Sweetalert2 modal

## Expected behavior

I expect to be able to click option 6 without the modal closing.

## Live demo 

https://jsfiddle.net/bytestream/swyngx62/1/

**Comment by bytestream** [comment]
I should add this behavior only affects Firefox, it works fine in Google Chrome (tested on latest Linux versions).

**Comment by limonte** [comment]
I'm able to reproduce, interesting. Thanks for reporting, I'll investigate this.

**Comment by limonte** [comment]
The issue is in `selectize.js` which selects the item not with the `click` event, but with the `mousedown` event, which isn't aligned with the native `<select>` and completely unexpected.

Either use more sensible plugin as Select2 or disallow backdrop clicks by setting [allowOutsideClick](https://sweetalert2.github.io/#allowOutsideClick) to `false`.

**Comment by bytestream** [comment]
Thanks for investigating @limonte ! I'll report pass this on to selectize
