### ISSUE TITLE
(after #2174) params passed via .mixin() no longer always treated the same as params passed via .fire()

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#2177]
@limonte This PR introduced quite a bit of complication, with the way mixin params are collected & treated separately from "user params" (params passed to `.fire`).. 

One regression is fixed by #2174 but there is more:

`Swal.mixin({...foo}).fire({...bar})` is no longer equivalent to `Swal.mixin({...foo}).mixin({...bar}).fire()`

Before this PR, the showClass options (from `foo` & `bar`) would never be merged. After this PR, those options will be merged in the first example but not in the second. (Same thing for hideClass.) I fear that if this complication is not dealt with, more differences will emerge (or at least it will be difficult to avoid) and that will make a more confusing API.
(The other issue here is that this showClass/hideClass merging behavior, which is not fully backwards compatible, was added in a patch release, without any notice.)

Also, before this PR, the `mixin` method accepted all the same options as `fire`. After this PR, the `mixin` method will ignore any given `template` option.

I think this PR and the solution described in #2131 took the wrong approach of fixing that issue...
See some more comments on that issue

_Originally posted by @zenflow in https://github.com/sweetalert2/sweetalert2/issues/2133#issuecomment-782005322_

**Comment by limonte** [comment]
@zenflow would you mind to submit a PR with a qunit test which will fail and demonstrate the issue that you're describing? Thanks!

**Comment by zenflow** [comment]
@limonte Sure. Btw we could change the title to something like "(after #2174) params passed via .mixin() no longer always treated the same as params passed via .fire()"

I can't easily add a test to really verify this spec (that "params always have the same effect regardless of whether passed via `.mixin()` or via .fire()`) since that would basically involve repeating all the the existing tests that test what each param does when passed via `.fire()`, which would be very expensive in terms of complexity (that or would be very WET/repetitive and still not really enforce the spec).
But I will add some tests that expose the cases where this spec is violated!

**Comment by limonte** [comment]
Thank you @zenflow, now I understand the issue.
