### ISSUE TITLE
Textarea with `px` width option should have correct width

### ISSUE THREAD

**Issue by taichunmin** [sweetalert2/sweetalert2#2291]
## Current behavior

```js
Swal.fire({
  input: 'textarea',
  width: 900, // no effect
})
```

## Expected behavior

Textarea with `px` width option should have correct width.

## Live demo 

https://codepen.io/taichunmin/pen/poPwROZ

---

Has SweetAlert2 helped you create an amazing application? You can show your support via GitHub Sponsors: https://github.com/sponsors/limonte

Alternative ways for donations (PayPal, cryptocurrencies, etc.) are listed here: https://sweetalert2.github.io/#donations

**Comment by BluchipStudio** [comment]
@limonte i have the same kind of issue i am commenting here instead of opening a new thread as it is a related issue and in the future it may help others searching for the same kind of thing

i am using the follwoing code 

```
const ipAPI = $(this).data("api")

const inputValue = fetch(ipAPI).then(response => response.text())

Swal.fire({
    title: 'LOADING LISTINGS',
    color: '#716add',
    input: 'textarea',
    width: '50%',
    inputLabel: 'Your Listings',
    inputValue: inputValue,
    showCancelButton: true,
})
```

the initial model loaded is 50% of the screen size but once the fetch has been completed and the model is reloaded to populate the input option the model size drop back to the default size making it impossible to read whats in the text area with out having to manually resize with the cursor and corner option of the text area
