### ISSUE TITLE
CSS Compilation Issue

### ISSUE THREAD

**Issue by tomshaw** [sweetalert2/sweetalert2#2301]
Using a default Laravel installation and importing the SCSS stylesheet, Sweet Alert is unable to compile due to the following error. 

import Swal from 'sweetalert2/dist/sweetalert2.js'
import 'sweetalert2/src/sweetalert2.scss'

```
warn - You have enabled the JIT engine which is currently in preview.
ERROR in ./node_modules/sweetalert2/src/sweetalert2.scss (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[7].oneOf[1].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[7].oneOf[1].use[2]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[7].oneOf[1].use[3]!./node_modules/sweetalert2/src/sweetalert2.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined function.
    ╷
517 │ $icon-zoom: math.div(strip-units($swal2-icon-size), 5);
    │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  node_modules\sweetalert2\src\scss\_core.scss 517:13  @import
  node_modules\sweetalert2\src\scss\_theming.scss 8:9  @import
  node_modules\sweetalert2\src\sweetalert2.scss 4:9    root stylesheet


```

**Comment by zenflow** [comment]
Ok, looks like this is happening because the `math.div` function used is available with the Dart Sass compiler but not with the LibSass compiler.. See https://sass-lang.com/documentation/modules/math#div

Sweetalert2's own build system uses the [Dart Sass](https://www.npmjs.com/package/sass) package.

We know (based on the error above) that Laravel is using [sass-loader](https://www.npmjs.com/package/sass-loader). The docs for that package say it can use either Node Sass (which uses LibSass) or Dart Sass, and I'm guessing your default Laravel installation is set up with Node Sass.

@tomshaw You could see about changing the Laravel installation to use the Dart Sass package instead of Node Sass.

**Comment by zenflow** [comment]
@limonte We could see about making Sweetalert2's scss code compatible with the other Sass compiler implementations. 

Looks like the plain `/` (division) operator is being deprecated due to conflict with the `/` separator in css, but that hasn't been completed yet, and (as far as I can see) the only currently portable/compatible way to divide is using the `/` (division) operator. See https://github.com/sass/sass/issues/2565

If I'm not mistaken, the `/` (division) operator should work without problems if the expression is wrapped in parenthesis: https://stackoverflow.com/a/22486831

**Comment by tomshaw** [comment]
Looks like it defaults to Node Sass. That should fix it. Thanks for the heads up.

**Comment by limonte** [comment]
> @limonte We could see about making Sweetalert2's scss code compatible with the other Sass compiler implementations.
> 
> Looks like the plain `/` (division) operator is being deprecated due to conflict with the `/` separator in css, but that hasn't been completed yet, and (as far as I can see) the only currently portable/compatible way to divide is using the `/` (division) operator. See [sass/sass#2565](https://github.com/sass/sass/issues/2565)
> 
> If I'm not mistaken, the `/` (division) operator should work without problems if the expression is wrapped in parenthesis: https://stackoverflow.com/a/22486831

Sass will throw warnings for each expression with `/`:

<img width="825" alt="CleanShot 2021-08-01 at 10 27 00@2x" src="https://user-images.githubusercontent.com/6059356/127762982-3c855def-0b8f-41b5-89ec-e54c96c9f23e.png">

And it's not possible to stop showing those warnings.

As I understand correctly Sass really wants to bring attention to this breaking change by such aggressive deprecation warnings.

Also, IMO they want people to stop using deprecated `node-sass` in favor of Dart Sass.

**Comment by fabioespinosa** [comment]
Can we just include the compiled CSS in the dist from npm?

**Comment by limonte** [comment]
> Can we just include the compiled CSS in the dist from npm?

It's included.

**Comment by fabioespinosa** [comment]
Yep, just saw it. Sorry for the noise!

**Comment by manolo-94** [comment]
I know this issue is a bit old but maybe this can help someone.

this was my problem:

[ng] Error: ./node_modules/sweetalert2/src/sweetalert2.scss
[ng] Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
[ng] ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
[ng] SassError: Undefined function.
[ng]   ╷
[ng] 5 │ $icon-zoom: math.div(strip-units($swal2-icon-size), 5);
[ng]   │             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ng]   ╵
[ng]   node_modules/sweetalert2/src/scss/_icons.scss 5:13   @import
[ng]   node_modules/sweetalert2/src/scss/_core.scss 542:9   @import
[ng]   node_modules/sweetalert2/src/scss/_theming.scss 8:9  @import
[ng]   node_modules/sweetalert2/src/sweetalert2.scss 4:9    root stylesheet


I was trying to run an old project using ionic and angular I was stuck with this problem for a couple of hours until I found this.

https://github.com/sweetalert2/sweetalert2/issues/2263#issuecomment-857722854

I just replaced the lines of code you mentioned and my project worked.
