### ISSUE TITLE
Support Angular 14

### ISSUE THREAD

**Issue by fensefernando** [sweetalert2/sweetalert2#2453]
## Current behavior
Install

When I try to install with command npm install --save sweetalert2, generate error. I use Angular 14.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @kolkov/angular-editor@2.0.0
npm ERR! Found: @angular/common@14.0.0
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^14.0.0 || ^15.0.0" from @angular/cdk@14.0.1
npm ERR!   node_modules/@angular/cdk
## Expected behavior
Not generate error

**Comment by limonte** [comment]
the provided log is unrelated to sweetalert2

**Comment by fensefernando** [comment]
Show this error on ng serve 

./node_modules/sweetalert2/src/sweetalert2.scss:1:0 - Error: Module parse failed: Unexpected token (1:0)
File was processed with these loaders:
 * ./node_modules/resolve-url-loader/index.js
 * ./node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
> .swal2-popup.swal2-toast {
|   box-sizing: border-box;
|   grid-column: 1/4 !important;

**Comment by DavidLC98** [comment]
Any solution for this issue?

I had to "import Swal from 'sweetalert2/src/sweetalert2.js'" instead of importing it from "sweetalert2" as limonte said in #2467 in order to fix CommonJS warning in Angular.

After the change, the alerts are no longer working as expected, the styles seems to be failing, so it's needed to "import 'sweetalert2/src/sweetalert2.scss'".

After the ng serve, an error occurs:
./node_modules/sweetalert2/src/sweetalert2.scss:1:0 - Error: Module parse failed: Unexpected token (1:0)
> File was processed with these loaders:
 ./node_modules/resolve-url-loader/index.js
 ./node_modules/sass-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
 .swal2-popup.swal2-toast {
|   box-sizing: border-box;
|   grid-column: 1/4 !important;

If you can help, it would be amazing, thanks!
