### ISSUE TITLE
Warning for using Commnjs in Angular 14.0.6

### ISSUE THREAD

**Issue by kyrolus** [sweetalert2/sweetalert2#2467]
## Current behavior
Warning: E:\Bussiness\Project\CodingBible\ClientApp\src\CommonServices\notifications.service.ts depends on 'sweetalert2'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

## Expected behavior
Stop depending on CommnJs

**Comment by limonte** [comment]
I guess importing sweetalert2 this way should help:

```diff
- import Swal from 'sweetalert2'
+ import Swal from 'sweetalert2/src/sweetalert2.js'
```

**Comment by kyrolus** [comment]
It works but without styling. How I get css of sweet alert with this solution

**Comment by limonte** [comment]
https://sweetalert2.github.io/#usage

**Comment by iGanja** [comment]
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by EliezerB123** [comment]
> I guess importing sweetalert2 this way should help:
> 
> ```diff
> - import Swal from 'sweetalert2'
> + import Swal from 'sweetalert2/src/sweetalert2.js'
> ```

When importing like that, we get the error:

> Could not find a declaration file for module 'sweetalert2/src/sweetalert2'. 'node_modules/sweetlaert2/src/sweetalert2.js' implicitly has an 'any' type.

and the only way I can resolve it is by adding a `global.d.ts` file to the root of my project next to tsconfig.json with the following:

> declare module 'sweetalert2/src/sweetalert2.js';

or else I need to add 

> "noImplicitAny": false

to my tsconfig.json, neither of which are ideal workarounds.

**Comment by geferon** [comment]
It seems like whenever Angular is compiling, it looks in the package.json for the following entries in this order:
- `es2015`
- `browser`
- `module`
- `main`

Because `browser` is present and is pointing at the CJS compilation, it's interpreting the package as being CJS.
To fix this, the package would require another `es2015` entry pointing to the ESM version.
Source: https://github.com/angular/angular-cli/issues/19936#issuecomment-771861779
