### ISSUE TITLE
Using themes

### ISSUE THREAD

**Issue by vnihoul77** [sweetalert2/sweetalert2#2469]
Good afternoon,
We're looking to use the themes, but we can't figure out how to do so - we're not very experienced developers.
We understand that we need to import the corresponding CSS file for the desired theme, but how do you then apply it?
My goal is to have a dropdown with the different themes and show the modal with the selected theme.

The easiest would be to have a "theme" parameter in the options as the other settings, but there are none.

EDIT: We already posted about this issue but the answer we received was referencing the same documentation page we're not able to understand.
Any additional help or examples we could look for?
Many thanks!

https://github.com/sweetalert2/sweetalert2-themes#usage

Originally posted by @limonte in https://github.com/sweetalert2/sweetalert2-themes/issues/94#issuecomment-1169228677

**Comment by MarioPerini** [comment]
This is not an Issue of sweetalert2, yes a theme parameter would be helpful in some cases but you can easy work around this.

If you want to change the theme just for dark mode you can use a media query like:
`<link href="/css/swal-dark.css" rel="stylesheet"
      media="(prefers-color-scheme:dark)">`

Otherwise like you try to do with a drop-down it gets a bit "hacky" 
you can add the disabled attribute on the link and just remove the one on the theme you want to show
Here is an example for you:
https://codepen.io/MarioPerini/pen/GRxPoWX

**Comment by limonte** [comment]
The solution above will work perfectly for a simple light/dark switch.

If you need a switch for more themes, I'd recommend this approach:

SCSS:

```scss
// Default SweetAlert2 styles
[data-theme='default'] {
  @import 'sweetalert2/src/sweetalert2.scss';
  // alternatively import from @sweetalert2/themes
  // @import '@sweetalert2/themes/default/default.scss';
}

// Dark theme
[data-theme='dark'] {
  @import '@sweetalert2/themes/dark/dark.scss';
}

// Bootstrap 4 theme
[data-theme='bootstrap-4'] {
  @import '@sweetalert2/themes/bootstrap-4/bootstrap-4.scss';
}
```

Then apply `data-theme` dynamically to `<html>` tag (`document.documentElement`):

```js
document.documentElement.setAttribute('data-theme', 'dark')
```
