### ISSUE TITLE
Russian pages play Ukrainian anthem

### ISSUE THREAD

**Issue by jonluca** [sweetalert2/sweetalert2#2552]
https://github.com/sweetalert2/sweetalert2/commit/7de8f7af35f4b0067edc4a735c5b9550537925c4

This commit adds what could be almost considered malware. Any navigator language that has ru in it will have the Ukrainian national anthem play.

Im all for supporting Ukraine but this does not feel like the right place.

**Comment by limonte** [comment]
> Any navigator language that has ru in it will have the Ukrainian national anthem play.

Not quite correct. There are 2 conditions: 1. navigator language that has ru and 2. a user is visiting website with russian URL.

> Im all for supporting Ukraine but this does not feel like the right place.

Every place is the right place if it helps russian infrastructure to stop functioning and therefore bringing the victory of Ukraine closer. There's a war here, it might be difficult to understand the situation here from NY, but there won't be peace. There will be victory of either one or another side and my responsibility is to help Ukraine to win.

**Comment by Berkays** [comment]
How is it supposed to stop russian infrastructure with this?

**Comment by docyx** [comment]
How about adding a simple donation link in the README instead of protestware? Because playing the Ukraine national anthem to the Russians against their will doesn't help anybody.

**Comment by limonte** [comment]
Hey fellas, I appreciate your feedback and I wonder where are you coming from? There's unusual amount of reactions in this thread which probably means there's a link somewhere to this issue. Where's that discussion?

**Comment by james-elicx** [comment]
> Hey fellas, I appreciate your feedback and I wonder where are you coming from? There's unusual amount of reactions in this thread which probably means there's a link somewhere to this issue. Where's that discussion?

Not another cringe lets poison open-source software 'activist'. Supply chain attacks through FOSS with your 'protestware' is not the way to go, nor should it be supported by anyone who is an advocate for open-source.

Why should one continue to trust this library, or you as a maintainer, in the future? I know I certainly never will. What if this is just the start of your protestware, what if one day you decide to add a release that wipes someone's hard drive because they use a Russian VPN server? There is no longer a foundation of trust in you as a maintainer to act in a responsible manner and publish releases that won't harm my users.

Releases like this set a dangerous standard.

For an example of another piece of protestware from a disgraceful maintainer earlier this year, see https://en.wikipedia.org/wiki/Peacenotwar

**Comment by limonte** [comment]
> Hey fellas, I appreciate your feedback and I wonder where are you coming from? There's unusual amount of reactions in this thread which probably means there's a link somewhere to this issue. Where's that discussion?

Right, `r/javascript` :) Welcome everybody, I am opened to your criticism. 

To clarify my intentions. I want to disallow using my work for the russian segment of the Internet, i.e. `.ru` and `.рф` websites. Changing the licence won't help because russians don't care about licences or laws, especially now. The directly admit this fact and they even proud of it. "we don't care about your sanctions and restrictions lol" - that's what they say generally, not everybody of course, but the vast majority.

Also, NATO now declares Russia as "significant and direct threat". I live in the country which is about to join NATO and you fellas are asking me to support "significant and direct threat" with my hard work? No way, sorry.

We will fix our souls and our software after the war. Now, it's not the right time to anyhow support the country that is considered as a terrorist state (or state sponsor of terrorism) by at least 5 EU countries.

**Comment by Sam-ThirdEye** [comment]
I fully agree with your decision. Glory to Ukraine

**Comment by docyx** [comment]
> Russian officials openly threatened Finland with nuclear strikes and you're asking me to be nice with them?!

We are not asking you to be nice. We are asking you to stop making a mockery of an incredibly sad situation. I get adding a donation link, but disabling pointer events and playing the Ukrainian anthem? You are not spreading awareness, you are trolling millions of people who have no control over what their government is doing. This is not helping.

**Comment by sam-cousins** [comment]
> > Russian officials openly threatened Finland with nuclear strikes and you're asking me to be nice with them?!
> 
> We are not asking you to be nice. We are asking you to stop making a mockery of an incredibly sad situation. I get adding a donation link, but disabling pointer events and playing the Ukrainian anthem? You are not spreading awareness, you are trolling millions of people who have no control over what their government is doing. This is not helping.

If you don't like it - don't use the software, it's as simple as that.

**Comment by docyx** [comment]
> If you don't like it - don't use the software, it's as simple as that.

limonte is free to do whatever he wants with his project, that's what open source is all about. That still doesn't mean we can't all have a healthy discussion about something that was changed.

**Comment by limonte** [comment]
To make the discussion even healthier make sure to check out the previous attempts:

- https://github.com/sweetalert2/sweetalert2/pull/2428
- https://github.com/sweetalert2/sweetalert2/pull/2462

All things are good in the right time. I was nice and raising awareness for them since April. Now it's too late to talk and change people's minds. Now it's time to play Ukrainian anthem for them.

**Comment by Berkays** [comment]
> To make the discussion even healthier make sure to check out the previous attempts:
> 
> * [Add STOP WAR message for Russians #2428](https://github.com/sweetalert2/sweetalert2/pull/2428)
> * [Better anti-war message for Russians #2462](https://github.com/sweetalert2/sweetalert2/pull/2462)
> 
> All things are good in the right time. I was nice and raising awareness for them since April. Now it's too late to talk and change people's minds. Now it's time to play the Ukrainian anthem for them.

Looks like people also didn't like the idea back then. It's seemed ironic for me that you don't have a single word about this topic in the main page but rather in the code.

**Comment by docyx** [comment]
The fact that you keep adding these changes despite all the disagreements and backlash just tells me you are either extremely childish and narrow minded or just doing it to get the attention. Either way I know nobody is going to change your mind, so you just keep doing you I guess

**Comment by limonte** [comment]
@docyx your "healthy discussion" is getting too personal, you're blocked now.

**Comment by looeee** [comment]
I'm taking a step back to think about why people are complaining about this. It's a cheeky anti-war message that targets people from the country waging an unjust war and I like those kind of messages. 

But... I don't like this.

The reason is about trust. The open source community is a trust-base ecosystem. When someone adds unrelated code of _any_ kind, it's a breach of trust.

Imagine if every open source library you use had this kind of stuff in it - this guy has anti war messages, another person has pro war messges, another person has ads for coca cola in obfuscated code, the next one has a bitcoin miner in it, and so on. All of us use _thousands_ of  open source libraries. We cannot ever check all of them, so we rely on a trust-based ecosystem. Allowing one message you like, or allowing job posting in console messages and so on, is a slippery slope. It erodes this trust and normalizes adding unrelated messaging to code. 

If you want to support Ukraine, do it upfront by adding a banner to your website. Add a heading to the Github readme, the docs, add a license saying people in Russia are not allowed to use your code, whatever. All of those are fine. 

I personally don't believe adding hidden stuff to your code is ever fine though. It is your code and your decision whether to keep it in, but you should understand why even people who support your message will dislike this.

**Comment by 7flash** [comment]
It feels like abuse of our trust in the code in favor of your emotional need to express anger invoked by your political views. Please, consider adding optional flag to disable this feature.

**Comment by Hammster** [comment]
I'm very interested to know if this isn't a conflict of interest with the code of conduct of the project? You maybe should add some note to it to make clear that you are willing to make exceptions.

Generally your software your choice, but i think projects should give people the knowlege to estimate risks, and also that people should honor that decision.

**Comment by Aarnihauta** [comment]
You are trusted and adding the virus undermines it. I can no longer trust any node modules. Today Russia, tomorrow Kazakhstan, the day after tomorrow - the entire post-Soviet space including Ukraine.

**Comment by limonte** [comment]
Right now russians are bombarding civil infrastructure if Ukraine, around 100 rockets today and russians are very happy with that in Telegram channels. 

I heard you all and I appreciate the feedback. My plugin will play Ukrainian anthem for them until the victory.

🇺🇦 Glory to Ukraine and its brave people. 🇺🇦 

PS. this is today's video of children hiding from russian rockets in the underground parking 😢 😢 😢 

https://user-images.githubusercontent.com/6059356/201969835-c8ea537a-8459-4af7-b9e9-2dcaeed79cc9.MP4

**Comment by limonte** [comment]
## ⚠️ The usage of this software for `.ru`, `.su`, and `.рф` domain zones is now prohibited 
 https://github.com/sweetalert2/sweetalert2#important-notice-about-usage-of-this-software-for-ru-su-and-%D1%80%D1%84-domain-zones
