### ISSUE TITLE
sweetalert2 v11.4.9 and above contains hidden functionality

### ISSUE THREAD

**Issue by farojas85** [sweetalert2/sweetalert2#2638]
### Current behavior

I have installed its version 11.7.12 and I get an alert in dependaBot from Github:

sweetalert2 versions 11.4.9 and above are vulnerable to hidden functionality that was introduced by the maintainer. The package outputs audio and/or video messages that do not pertain to the functionality of the package and is not included in versions 11.0.0 - 11.4.8.

Workaround
Use a version 11.0.0 - 11.4.8 of the package until the maintainer releases a fix.

### Expected behavior

be resolved!

### Live demo !!! THIS FIELD IS REQUIRED !!!

The live demo template: https://codepen.io/limonte/pen/JjoWRMx

**Comment by zenflow** [comment]
@farojas85 duplicate issues much?

**Comment by farojas85** [comment]
The first time I see in a recently created project.
In my previous projects this issue did not appear,

**Comment by zenflow** [comment]
@farojas85 good to know

anyways here's another issue with the **exact** same title: #2574

**Comment by farojas85** [comment]
@zenflow  Thank you.
For now I will use version 11.4.8.

**Comment by limonte** [comment]
This is starting to bother me as well, I'll try to get rid of the vulnerability because it's invalid. The functionality is not "hidden" and clearly documented in the README.

**Comment by limonte** [comment]
https://github.com/github/advisory-database/pull/2409

**Comment by zenflow** [comment]
Hi @limonte I see there is some difficulty having the advisory completely removed..
I think it could be completely removed since the functionality is no longer hidden..
Another possible way to deal with this if that can't happen: Isn't there a version where the functionality became "unhidden", i.e. documented in the README? We could take that into account in the "Affected versions" (e.g. if the functionality became unhidden in 11.5.1 use version range `>= 11.4.9 < 11.5.1`).
