### ISSUE TITLE
How to realize customized sweetAlert2 library ? 

### ISSUE THREAD

**Issue by jakesungjaekim** [sweetalert2/sweetalert2#2641]
Hello, 
In the NEXT framework, i just want to realize library which is customized by my self.
i wanted to customize something which is related to CSS like padding, top, margin... etc
so i fixed library and use patch-package and then i got patches folder and patched css file.
but when i run build, i cannot see customized css code. why i faced this problem? 
i appreciate if you give some solution. thank you.

this is sample which is shown changed code by patch-package.

``` 
sweetAlert2/ dist / sweetAlert2.css  

 body.swal2-toast-shown .swal2-container.swal2-top {
-  top: 0;
+  top: 100px;
   right: auto;
   bottom: auto;
   left: 50%;
   transform: translateX(-50%);
 }


```

**Comment by zenflow** [comment]
@jakesungjaekim Probably you are using the main module which is the compiled js **and css** https://github.com/sweetalert2/sweetalert2/blob/5d941b61854c08df5f393c773c83310d64c1cb2d/package.json#L7

For your approach you probably want to import the js and css separately:

```diff
-import Swal from 'sweetalert2'
+import 'sweetalert2/dist/sweetalert2.css'
+import Swal from 'sweetalert2/dist/sweetalert2.js'
```

As an alternate approach, instead of messing with patch-package, you could just create your own css file where you override padding, top, margin, etc.

**Comment by jakesungjaekim** [comment]
wow ! can i ask.. how to import new css file in package.json ? 

and i also ask, when i used patch-packge, i can get changed css code what i want.
in this point, package.json will run changed css file. 
what i missed something?

**Comment by jakesungjaekim** [comment]
aaaa i can know something!!

**Comment by zenflow** [comment]
@jakesungjaekim You're welcome dude! All the best!

**Comment by jakesungjaekim** [comment]
@zenflow i have something question thogh.., i said i made it, so i fixed code minutely, 
and then i used to it i did, but i can`t see different. why i faced this problem? could you advice about this?

**Comment by zenflow** [comment]
I'm sorry. I don't know what you're saying.

Did my suggestion not work?

**Comment by jakesungjaekim** [comment]
first time, your suggestion work. but since once, it isn`t work. 
Once changed, it fails to render another change.

**Comment by zenflow** [comment]
That's probably because of Next's build cache.
Try this: stop Next dev server, delete the `.next` folder, and start Next dev server again.

I will suggest this again:
You will have a much easier time creating your own css file with your custom styles, and get rid of patch-package.
You are not meant to edit files in node_modules.
Patch-package allows you to do this, and it's very useful **when it's necessary**, but in this case it's not necessary.

**Comment by jakesungjaekim** [comment]
@zenflow I will try according to your advice. Are you saying that it is possible to modify external libraries without patch-package?

**Comment by zenflow** [comment]
@jakesungjaekim No, I am not saying that. I am saying that there is **no need** to modify this external library for your purpose (to customize style). 

Instead of modifying this library, just create your own css file

```css
/* css/my-custom-sweetalert2-styles.css */
 body.swal2-toast-shown .swal2-container.swal2-top {
  top: 100px !important;
 }

**Comment by jakesungjaekim** [comment]
@zenflow aaaa ~! i understood what you are saying. Thank you so much !! dude.

**Comment by zenflow** [comment]
@jakesungjaekim no problem dude.. good luck!

**Comment by jakesungjaekim** [comment]
@zenflow 

Yesterday, you told me that I could create my own CSS file to approach this problem. So, if that's the case, should I create a CSS file in my src/ subfolder and import the CSS file using cascading as follows?

```
+import 'sweetalert2/dist/sweetalert2.css'
+import Swal from 'sweetalert2/dist/sweetalert2.js'
+import 'css/my-custom-sweetalert2-styles.css'
```
Is that correct?

**Comment by zenflow** [comment]
@jakesungjaekim Basically, yes. You don't need to import SweetAlert2 js & css separately anymore though
