### ISSUE TITLE
Ability to disable auto focus on close button

### ISSUE THREAD

**Issue by maxkopych** [sweetalert2/sweetalert2#2735]
### New feature motivation

Probably should have option to disable auto focus on close button
![image](https://github.com/sweetalert2/sweetalert2/assets/10473755/5e39b9b6-5907-49bc-814f-5297df26d134)

Right now I'm creating hack to prevent it:
```
didOpen: () => {
    if (document.activeElement?.classList.contains("swal2-close")) {
        document.activeElement.blur();
    }
},
```

**Comment by limonte** [comment]
Hello @maxkopych and thanks for the nice request 🙌 

Blurring the focused element isn't quite accessible, I wouldn't recommend that.

Instead of that, I added the support for elements with [`autofocus` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus): https://github.com/sweetalert2/sweetalert2/pull/2736

Also, the example from your screenshot is updated now to reflect the changes: https://sweetalert2.github.io/#custom-html

Hopefully, that would also work for you.
