### ISSUE TITLE
Feature request: *ButtonTextColor properties

### ISSUE THREAD

**Issue by vanodevium** [sweetalert2/sweetalert2#2740]
### New feature motivation

It is now possible to customize buttons colors via properties passed as options to the **fire** method:
- **confirmButtonColor**
- **denyButtonColor**
- **cancelButtonColor**

In general, it is possible to specify the color of the text of the entire modal content (via **color** option), but the possibility to customize the color of the text inside the button is also missing.
In my opinion, it would be very convenient.
Something like
- **confirmButtonTextColor**
- **denyButtonTextColor**
- **cancelButtonTextColor**

Thanx!

**Comment by limonte** [comment]
Thanks for the request @vanodevium 

All these styling params are in my opinion a mistake, but it's too late to remove them 😄 

I certainly won't add any more of them. In order to customize the text color of buttons use `customClass` + CSS:

```js
Swal.fire({
  showCancelButton: true,
  customClass: {
    confirmButton: 'my-cool-button',
    cancelButton: 'my-cool-button'
  }
})
```

```css
.my-cool-button {
  color: red;
}
```

PS. while answering your question I actually found a bug in the library, make sure to upgrade `sweetalert2` dependency to the latest version v11.12.2 to use the suggested above solution.

**Comment by vanodevium** [comment]
@limonte Oh, I see. Ok.

Please suggest a possible solution:
I don't have the ability to pre-create classes, the color of the text is only in a dynamic variable that comes from the server.
How can I assign a color to the button text?

**Comment by limonte** [comment]
Colors for buttons of a popup dialog are coming from the server?! I'm helpless here, sorry.
