### ISSUE TITLE
CSS Animations not working on SWAL2 elements

### ISSUE THREAD

**Issue by treece** [sweetalert2/sweetalert2#650]
If you increase the transition background-color duration it doesn't work as expected. So for example, if increase the transition duration to 2s, on open it doesn't transition the 2s duration and on exit the container gets removed before the transition finishes.

Here's a jsfiddle example:
https://jsfiddle.net/treece/r2n743e7/

**Comment by acupajoe** [comment]
This one is pretty interesting! Sweetalert works by appending a new element to the DOM and removing it when it is closed. Browsers, to make things more efficient, seem to ignore CSS transitions on appended elements (see explanation [here](https://stackoverflow.com/a/24195559/3629438)). 

This means two solutions: 
- Refactor SWAL2 to always have its elements in the DOM
- Dynamically add a class after the element has rendered

For sake of ease, we'll take the second route and add a class to make the background transition work. 

See my example fiddle:
https://jsfiddle.net/r2n743e7/1/

**Comment by acupajoe** [comment]
Renamed to generalize to all transitions for the sake of other users that may search for this question.

**Comment by limonte** [comment]
Hello @treece and many thanks for reporting about this regression which was introduced when we switched from having permanently one DOM element in the document to dynamically adding/remove `.swal-container`.

I believe it's fixed in https://github.com/limonte/sweetalert2/pull/654 and if you're able to verify fix please do so. Step to verify:

1. Clone the swal2 repo
2. Clone the branch with the fix:
```
git fetch origin
git checkout -b fix/backdrop-animation origin/fix/backdrop-animation
git merge master
```
3. Build dist files by running `gulp` inside the `sweetalert2` folder
4. Open `index.html` and test

PS @acupajoe many thanks for handling some issues and providing a useful feedback! In this case, your feedback helped me to understand and (hopefully) fix this issue.

**Comment by treece** [comment]
@limonte Awesome, thanks! I will test it later today 😉

**Comment by limonte** [comment]
@treece my apologies, PR isn't ready yet because of the [small regression](https://github.com/limonte/sweetalert2/pull/654#issuecomment-334988709). I will notify you here when I come up with the proper solution.
