### ISSUE TITLE
Bower package points to old repo.

### ISSUE THREAD

**Issue by JanisGruzis** [sweetalert2/sweetalert2#799]
Bower package points to old repository.

https://github.com/limonte/sweetalert2

instead of

https://github.com/sweetalert2/sweetalert2

easy to check in https://bower.io/search/

**Comment by limonte** [comment]
Thanks @JanisGruzis for keeping track on our today's migration process and reporting this issue!

Here's the screenshot I got from Bower:

![](https://i.imgur.com/WbJKxFj.png)

Considering that the current number of stars is 4074 and Bower shows 4035, I suspect some cache on the Bower side, my guesstimate that this cache is 2-3 days old.

Let's ways for a couple of days and recheck bower.io, it should be fine since I updated related fields:

- https://github.com/sweetalert2/sweetalert2/blob/master/bower.json#L3
- https://github.com/sweetalert2/sweetalert2/blob/master/bower.json#L42

**Comment by feyrkh** [comment]
An FYI - this is causing build failures for us. If a resolution to this can possibly be reached sooner than a few days, that would be much appreciated.
```
[ERROR] bower sweetalert2#=0.2.1  ENORESTARGET No tag found that was able to satisfy =0.2.1
[ERROR] 
[ERROR] Additional error details:
[ERROR] No versions found in https://github.com/limonte/sweetalert2.git
```

**Comment by arturskeeled** [comment]
Meanwhile @JanisGruzis and @feyrkh you can use:

"dependencies": {
    "sweetalert2": "https://github.com/sweetalert2/sweetalert2.git#7.3.1"
}

**Comment by limonte** [comment]
Poor deprecated Bower is the :snail: 

I did `unregister sweetalert2` and then registered it again, but it still shows outdated infor for the package. Sorry, guys, this is not in our hands :(

**Comment by limonte** [comment]
```sh
curl https://registry.bower.io/packages/sweetalert2
{"name":"sweetalert2","url":"https://github.com/sweetalert2/sweetalert2.git"}
```

**Comment by limonte** [comment]
## bower cache clean

**Comment by limonte** [comment]
![image](https://user-images.githubusercontent.com/6059356/34725894-03099f56-f55b-11e7-9f1d-c247ea3ff2cc.png)
