### ISSUE TITLE
swal.disableConfirmButton() not working

### ISSUE THREAD

**Issue by tavuntu** [sweetalert2/sweetalert2#865]
I just noticed this does not work and throws a `"ERROR TypeError: sweetalert2_1.default.disableConfirmButton is not a function"`

To reproduce just create a new project with Angular CLI (I'm using version 1.6.6) and modify app.component.ts a bit:

```typescript
import { Component } from '@angular/core';
import swal from 'sweetalert2';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor() {
    swal.disableConfirmButton();// <-- this doesn't work
    swal("sfsdfdsfd");// <-- this works fine
  }
}
```

**Comment by toverux** [comment]
Yes, those DOM-related functions are created **after** the first modal is shown. They do not set a state on which the button state is based: these are imperative DOM manipulations.

That's why I use thunks here (see comment): https://github.com/sweetalert2/ngx-sweetalert2/blob/master/src/swal-partial-targets.ts#L3

You first need to display a swal to use `disableConfirmButton()`. You can use the `onOpen` hook to call it (it is called before the modal is shown, but when its DOM is already created, therefore you won't see the button "blink"):

```js
swal({
  onOpen: () => swal.disableConfirmButton()
});
```

**Comment by tavuntu** [comment]
I see, thanks for the answer!

**Comment by toverux** [comment]
@limonte I think this can be closed? Maybe one day we'll have some kind of modal instances and not just utility function to manipulate the modals' DOM, but this is another story.

**Comment by tavuntu** [comment]
yes, I'm closing this

**Comment by tavuntu** [comment]
oops, sorry, thought that msg was for mee

**Comment by limonte** [comment]
Yup, I don't have anything to add to @toverux's comments. Closing the issue.

**Comment by zenflow** [comment]
Reopening this so I can close it with a fix 😋

**Comment by zenflow** [comment]
> I think this can be closed? Maybe one day we'll have some kind of modal instances and not just utility function to manipulate the modals' DOM, but this is another story.

@toverux @limonte It is possible to change the [new `context` object](https://github.com/sweetalert2/sweetalert2/blob/54d78d5499b8ec2e8b46ed30f2cc67d8ff1775d9/src/sweetalert2.js#L420) to a class instance and move code into instance methods. In fact the only reason I didn't do this in #969 was to avoid the huge code change that's hard to review and can result in merge conflicts.
