### ISSUE TITLE
Calling swal.close() does not call the onClose callback

### ISSUE THREAD

**Issue by rkyoku** [sweetalert2/sweetalert2#919]
Calling `swal.close()` does not call the `onClose` callback. It does work, though, when calling `swal.clickCancel()`.

```
swal({
	onClose: () => {
		console.log('not being called');
	}
});

if (swal.isVisible()) {
	swal.close();
}
```

https://jsfiddle.net/ad3quksn/436/

**Comment by zenflow** [comment]
@RenaudParis Thanks for opening this issue, with reproduction

Hmm. Yeah, that behavior seems wrong.

We should probably restrain from fixing it in this major though, since it's a breaking change and might cause issues in some projects.

As a temporary workaround, maybe use `swal.clickConfirm` or `swal.clickCancel` instead of `swal.close`. You can use those even if the buttons aren't visible.

**Slightly off-topic** Open question - What would you expect to happen with the current swal's Promise when you use `swal.close`? Currently it's left in a pending state.

**Comment by RenaudParis** [comment]
@zenflow Yes I'm calling `swal.clickCancel()` for now ;-)

But before that, I was calling `swal.close()` and I was wondering why my popup would not open a second time. I have a hidden div somewhere that I put inside the popup during `onBeforeOpen` and that I put back inside `body` during `onClose`. The `onClose` callback not being called, my div was purely being removed from the DOM ^^

Feel free to fix this whenever you deem reasonable, as it is non-blocking (it works with `clickCancel`, as stated).

Regarding your last question, please don't mock me, but I'm not using promises because my Grunt TS plugin would not recognize it (which saddens me regarding the `inputValidator` feature when mimicking a `prompt`).

Isn't the Promise already returning some data with a property like `dismiss` or something? (which informs the reason the popup was closed, when applicable, and allows for a more fine-grained behavior)

**Comment by zenflow** [comment]
> Isn't the Promise already returning some data with a property like dismiss or something? (which informs the reason the popup was closed, when applicable, and allows for a more fine-grained behavior)

Yes, the promise **normally** resolves with an object with either `dismiss` (indicating how it was dismissed) or `value` (the return value), but if you call `swal.close` then the promise never resolves. I am wondering if this is the best behavior, or if it should dismiss, or something else.

**Comment by RenaudParis** [comment]
IMHO, it should always provide an information regarding what triggered it (cancel button, close button, click on overlay, validation, whatever).

It does not cost anything (I think) to do it, and it provides information that may be of value in some cases.

What do you think?

**Comment by zenflow** [comment]
Thanks for joining the discussion @RenaudParis!

My only apprehension about "always provide an information regarding what triggered it" is that "dismissals" (currently) are something that the user does. I don't want to change the meaning of "dismiss" by adding a new type of dismissal that is done programatically. 

So what if we resolved the promise with `{}` (no `value` or `dismiss`)?

**Comment by RenaudParis** [comment]
You're probably right not to mix end-user and developer actions, and I guess your solution should be fine and would allow the exact same granularity!

Again, I am not used to swal internal code, but from an external POV, what you are suggesting makes perfect sense :)

**Comment by limonte** [comment]
> So what if we resolved the promise with `{}` (no `value` or `dismiss`)?

good idea 👍

@gverni would you mind handling this one?

**Comment by limonte** [comment]
Done in #1379
