### ISSUE TITLE
In Reddit app embedded browser (latest iOS) it screws up scroll position when opens

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#920]
From https://www.reddit.com/r/webdev/comments/7xput6/sweetalert2_a_beautiful_responsive_highly/dua7w9j/

I can reproduce this issue, but I have no idea how to fix it. Any help would be very welcome!

**Comment by FranciscoG** [comment]
Hi, coming here from the reddit discussion

> it screws up scroll position on mobile when it opens
> Using the Reddit app embedded browser on an iPhone X with the latest OS

I'm on **iOS 11.2.5** and I downloaded the reddit app to test out what's happening and this is what I see:

When I tap one of the buttons to show a SWAL box the bottom of the screen jumps up to what looks like the exact height of the iOS Safari bottom nav toolbar.  If you look at the site on iOS and you start scrolling enough so that the bottom toolbar goes away, tap on a button to show a SWAL and the 
bottom toolbar pops up again.  

is this what the user meant by "screws with the scroll position" ?

Are you doing anything in JS to make that toolbar show up on iOS or is iOS handling automatically in response to some JS method your firing? It looks like that toolbar is disabled in embedded browser so you're just seeing white space

**Comment by limonte** [comment]
Thanks @FranciscoG for trying to resolve this issue. It should be fixed it in the latest release, please check: https://sweetalert2.github.io
