### ISSUE TITLE
The long content example doesn't work properly in IE11

### ISSUE THREAD

**Issue by limonte** [sweetalert2/sweetalert2#933]
Live demo: https://sweetalert2.github.io/#long-text

Expected: the whole popup is visible

Actual: the top part of the popup is cropped

I can't figure out why IE11 isn't happy with the current flex layout and styles, any help would be very welcome!

**Comment by gverni** [comment]
Hi @limonte i'm still at the beginning of the debugging, but my first try was to set: 

 .swal2-container.swal2-center {
    align-items: flex-start; }

which in my understanding of flex should place the container aligned to the top of the block.  

Setting that, it works fine with IE11 and Chrome (haven't tried with other browser yet). I've also noticed that chrome behaves correctly regardless of this properties (i.e. you can remove it and still the top of the pop-up is shown correctly). 

I'll do some more research and let you know

**Comment by limonte** [comment]
Thank you for researching this issue @gverni! PR would be warmly welcome!

**Comment by limonte** [comment]
💰 I will donate $5 - $10 for the PR with the fix for this issue (donation will be done after approval and merge).

**Comment by gverni** [comment]
Hi @limonte I've been doing some research after my failed PR. As you know, the sweet alert uses a mix of align-items center and margins to make sure that the pop-up is centered (when smaller than the browser window) or aligned to the top (when it's bigger than the browser window). This doesn't work on IE because of the way the margins are handled. I tried "playing" with the margins and set different values, but those seems to be completely ignored by IE11. The only way i could centre it was to use javascript to check if there is a negative offset on the sweet alert container after a window resize event. But this seems to me more like an hack. If you are happy with a javascript solution, then i'm happy to submit a PR for review (no need for the bounty for that :-))

**Comment by limonte** [comment]
Thanks for your feedback @gverni!

> The only way i could centre it was to use javascript to check if there is a negative offset on the sweet alert container after a window resize event. But this seems to me more like an hack. If you are happy with a javascript solution, then i'm happy to submit a PR for review

Please do so. JS solution is 243324431324.12% better than no solution :) I'll be happy to review it.
