### ISSUE TITLE
InputAttributes should accept (boolean | string | number) values

### ISSUE THREAD

**Issue by rafaelss95** [sweetalert2/sweetalert2#957]
As you can see here: https://github.com/sweetalert2/sweetalert2/blob/138b5c87e84cb73e917c2efb81a5578b17067391/sweetalert2.d.ts#L632

... `inputAttributes` only accepts `string` values, however even in [examples](https://sweetalert2.github.io/), you can see `maxLength` _attribute_ being passed as `number`.

Also, I think it could accept also `boolean` allowing people to do something like:

```
inputAttributes: {
  autofocus: true
  // ...
}
```

<hr>

Also, I think the `inputValue` parameter should be `boolean | number | string` instead of `any`:

https://github.com/sweetalert2/sweetalert2/blob/138b5c87e84cb73e917c2efb81a5578b17067391/sweetalert2.d.ts#L602

**Comment by toverux** [comment]
Hello @rafaelss95, thanks for your careful read of the declaration file :)

> ... inputAttributes only accepts string values, however even in examples, you can see maxLength attribute being passed as number.

SweetAlert2 [uses `Element.setAttribute`](https://github.com/sweetalert2/sweetalert2/blob/138b5c87e84cb73e917c2efb81a5578b17067391/src/sweetalert2.js#L972), which [takes a `string` for the attribute values](https://github.com/Microsoft/TypeScript/blob/32c63a26284c0fcf6dfbdce709f3da680c2940d9/lib/lib.dom.d.ts#L3640). In fact, HTML attributes can only bear string values, don't forget that. If you set a number like `42`, it will be stored as `"42"` because JavaScript would call `.toString()` on anything that's not already a string. That's why passing a number will "work", but technically you can also pass objects, symbols, space shuttles and cats. But this is wrong as JS will perform type coercion.

![image](https://user-images.githubusercontent.com/1343250/36717583-ea696d40-1b9e-11e8-9dd7-82d0a82c4612.png)

In TypeScript, you'll have to be stricter here and explicitely use `toString()`, so you are explicitely transforming the value (and don't let the JS engine do it magically).

The same goes for `inputValue`, SweetAlert2 uses `HTMLInputElement.value`, which [exclusively takes strings](https://github.com/Microsoft/TypeScript/blob/32c63a26284c0fcf6dfbdce709f3da680c2940d9/lib/lib.dom.d.ts#L5484).

**Comment by toverux** [comment]
Erratum: you're partially right on `inputValue?: any` as it should be `inputValue?: string`.
Would you like to submit a PR?

**Comment by rafaelss95** [comment]
Yes, I'd like to submit a PR, however I have a last question:

Won't be strange if the `inputValue` only accepts` string`, since it can return a numeric `value`, for example, which is the case of `checkbox`?

[See this example](https://stackblitz.com/edit/angular-gitter-5bjtnv)(Just open console and press "Continue").

**Comment by toverux** [comment]
Hm, that's strange, indeed. But since SweetAlert still passes the value to something that takes a string, I'd say that we should mark it as a string.

After all, if SweetAlert2 was written in TypeScript, unless using `any`, inputValue would necessarily be a string (so it can be passed to `HTMLInputElement.value`).

The output having a different type is another problem I think. Let's type the input correctly :)

**Comment by toverux** [comment]
@rafaelss95 Still interested in making a PR? Or maybe you're unconvinced?
I'll handle it soon if you don't make it. It's a 5-minutes fix, but we're trying to encourage the community to contribute :)

**Comment by rafaelss95** [comment]
@toverux Just submtted a PR. Please, have a look and let me know if I'm missing something..
