### ISSUE TITLE
[Docs] - Default value for optional parameters

### ISSUE THREAD

**Issue by rafaelss95** [sweetalert2/sweetalert2#959]
Actually, all optional parameters in docs are annotated with `@default null`, as below:

https://github.com/sweetalert2/sweetalert2/blob/138b5c87e84cb73e917c2efb81a5578b17067391/sweetalert2.d.ts#L249-L255

... however, when you write `imageUrl?: string`, it will become `string | undefined`, under `strictNullChecks` flag, as you can see here in this test:

![imageedit_2_4670335967](https://user-images.githubusercontent.com/11965907/36703465-87cb0fe0-1b3a-11e8-8a27-f65aae760153.png)

if you want really `null`, instead of `undefined`, the parameters should be declared like this:

`imageUrl: string | null`.

**Comment by toverux** [comment]
Hello @rafaelss95,

Good point. I'm hesitating on what to do, though.

 - Either we keep `| undefined` and change for `@default undefined`
 - Keep `| undefined` but also add `| null` everywhere (because in fact, the library supports both).

The latest is closer to the library internals: https://github.com/sweetalert2/sweetalert2/blob/master/src/utils/params.js

However, I prefer the first because it makes the intent clearer, makes the declaration simpler and shouldn't impact the way you use the library.

**Comment by rafaelss95** [comment]
I'd go with the first option also.

```
/**
 * @default undefined
 */
imageUrl?: string;
```
